import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const vaultPath = process.env.OBSIDIAN_VAULT_PATH ?? "C:\\Obsidian\\Dev";
const outDir = path.join(
  vaultPath,
  ".obsidian",
  "plugins",
  "obsidian-task-viewer"
);

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const copyStaticFiles = {
  name: 'copy-static-files',
  setup(build) {
    build.onEnd(() => {
      try {
        // 1. Generate styles.css locally
        const cssDir = 'src/styles';
        const cssFiles = [
          '_variables.css',
          '_base.css',
          '_timeline-grid.css',
          '_timeline-date-header.css',
          '_timeline-allday.css',
          '_habits.css',

          '_timeline-drag.css',

          '_schedule.css',
          '_task-card.css',
          '_deadline.css',
          '_checkboxes.css',
          '_toolbar.css',
          '_pomodoro.css',
          '_timer-widget.css',
          '_modal.css',
          '_deprecated.css'
        ];

        const cssFilesSet = new Set(cssFiles);
        const allCssFiles = fs
          .readdirSync(cssDir, { withFileTypes: true })
          .filter((entry) => entry.isFile() && entry.name.endsWith('.css'))
          .map((entry) => entry.name);
        const unregistered = allCssFiles.filter((name) => !cssFilesSet.has(name));
        if (unregistered.length > 0) {
          console.warn(
            `Warning: Unregistered CSS files in ${cssDir}: ${unregistered.join(', ')}`
          );
        }

        let cssContent = '';
        for (const file of cssFiles) {
          const filePath = path.join(cssDir, file);
          if (fs.existsSync(filePath)) {
            cssContent += fs.readFileSync(filePath, 'utf8') + '\n';
          } else {
            console.warn(`Warning: CSS file not found: ${filePath}`);
          }
        }
        fs.writeFileSync(path.join(outDir, 'styles.css'), cssContent);

        // 2. Copy files to outDir
        fs.copyFileSync('manifest.json', path.join(outDir, 'manifest.json'));

        console.log('Built to ' + outDir);
      } catch (e) {
        console.error('Failed to copy static files:', e);
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outDir, "main.js"),
  plugins: [copyStaticFiles],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
