import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const outDir = "C:\\Obsidian\\Dev\\.obsidian\\plugins\\obsidian-task-viewer";

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

const copyStaticFiles = {
  name: 'copy-static-files',
  setup(build) {
    build.onEnd(() => {
      try {
        // 1. Generate styles.css locally
        const cssDir = 'src/styles';
        const cssFiles = [
          '_variables.css',
          '_base.css',
          '_timeline-grid.css',
          '_timeline-date-header.css',
          '_timeline-allday.css',
          '_timeline-future.css',
          '_timeline-drag.css',
          '_kanban.css',
          '_schedule.css',
          '_task-card.css',
          '_checkboxes.css',
          '_toolbar.css',
          '_deprecated.css'
        ];

        let cssContent = '';
        for (const file of cssFiles) {
          const filePath = path.join(cssDir, file);
          if (fs.existsSync(filePath)) {
            cssContent += fs.readFileSync(filePath, 'utf8') + '\n';
          } else {
            console.warn(`Warning: CSS file not found: ${filePath}`);
          }
        }
        fs.writeFileSync('styles.css', cssContent);

        // 2. Copy files to outDir
        fs.copyFileSync('manifest.json', path.join(outDir, 'manifest.json'));
        fs.copyFileSync('styles.css', path.join(outDir, 'styles.css'));
        fs.copyFileSync('main.js', path.join(outDir, 'main.js'));

        console.log('Built locally and copied to ' + outDir);
      } catch (e) {
        console.error('Failed to copy static files:', e);
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [copyStaticFiles],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}