/**
 * Timer target ID management: ensure, cleanup, resolve tasks.
 */

import type { TimerInstance } from './TimerInstance';
import { describeTimerAnchor, isDailyTimer } from './TimerInstance';
import type { TimerContext } from './TimerContext';
import type { TimerStorageUtils } from './TimerStorageUtils';
import { TimerTaskResolver } from './TimerTaskResolver';
import { type Task, isTvInline } from '../types';
import { logError, logWarn } from '../log/log';

export class TimerTargetManager {
    private resolver: TimerTaskResolver;

    constructor(
        private ctx: TimerContext,
        private storageUtils: TimerStorageUtils,
    ) {
        this.resolver = new TimerTaskResolver(ctx.plugin);
    }

    // ─── Ensure ──────────────────────────────────────────────

    async ensureTimerTargetId(timerId: string): Promise<void> {
        const timer = this.ctx.timers.get(timerId);
        if (!timer) return;
        // デイリーノート起点は対象行が無い。目印は自分が書いたレコード行の
        // `^id` が持つので、ここで足すものは無い。
        if (isDailyTimer(timer)) return;

        if (timer.timerTargetId) {
            timer.autoGeneratedTargetId = this.storageUtils.isAutoManagedTimerTargetId(timer.timerTargetId);
            this.ctx.persistTimersToStorage();
            return;
        }

        if (isTvInline(timer)) {
            await this.ensureInlineTimerTargetId(timer);
        }
    }

    private async ensureInlineTimerTargetId(timer: TimerInstance): Promise<void> {
        const taskIndex = this.ctx.plugin.getTaskIndex();
        const currentTask = this.resolveInlineTaskForTimer(timer);
        if (!currentTask) {
            logWarn(`[TimerTargetManager] inline target not resolved at start, timer runs without an anchor (${describeTimerAnchor(timer)})`);
            return;
        }

        if (currentTask.timerTargetId) {
            timer.taskId = currentTask.id;
            timer.taskFile = currentTask.file;
            timer.taskOriginalText = currentTask.originalText;
            timer.timerTargetId = currentTask.timerTargetId;
            timer.autoGeneratedTargetId = this.storageUtils.isAutoManagedTimerTargetId(currentTask.timerTargetId);
            this.ctx.persistTimersToStorage();
            return;
        }

        if (currentTask.blockId) {
            timer.taskId = currentTask.id;
            timer.taskFile = currentTask.file;
            timer.taskOriginalText = currentTask.originalText;
            timer.timerTargetId = currentTask.blockId;
            timer.autoGeneratedTargetId = false;
            this.ctx.persistTimersToStorage();
            return;
        }

        const newTargetId = this.storageUtils.generateTimerTargetId();
        try {
            // 付けられなかった id を探しに行かない。理由は書き込みの層が通知済み。
            if (!(await taskIndex.updateTask(currentTask.id, { blockId: newTargetId }))) return;
            await taskIndex.waitForScan(currentTask.file);

            const updatedTask =
                this.findInlineTaskByTimerTargetId(currentTask.file, newTargetId)
                || this.resolveInlineTaskForTimer(timer);
            if (updatedTask) {
                timer.taskId = updatedTask.id;
                timer.taskFile = updatedTask.file;
                timer.taskOriginalText = updatedTask.originalText;
                timer.timerTargetId = newTargetId;
                timer.autoGeneratedTargetId = true;
                this.ctx.persistTimersToStorage();
            }
        } catch (error) {
            logError(`[TimerWidget] Failed to assign timer target ID for inline task: ${(error as Error)?.message ?? error}`);
        }
    }

    // ─── Cleanup ─────────────────────────────────────────────

    async cleanupGeneratedTargetId(timer: TimerInstance): Promise<void> {
        if (!timer.autoGeneratedTargetId) return;
        if (!timer.timerTargetId) return;
        if (!this.storageUtils.isAutoManagedTimerTargetId(timer.timerTargetId)) return;
        if (this.hasAnotherActiveTimerWithTarget(timer.timerTargetId)) return;

        if (isTvInline(timer)) {
            await this.removeInlineTimerTargetId(timer);
        }
    }

    private hasAnotherActiveTimerWithTarget(timerTargetId: string): boolean {
        for (const timer of this.ctx.timers.values()) {
            if (timer.timerTargetId === timerTargetId) {
                return true;
            }
        }
        return false;
    }

    private async removeInlineTimerTargetId(timer: TimerInstance): Promise<void> {
        const taskIndex = this.ctx.plugin.getTaskIndex();
        let targetTask: Task | undefined;

        if (timer.taskFile) {
            targetTask = this.findInlineTaskByTimerTargetId(timer.taskFile, timer.timerTargetId!);
        }
        if (!targetTask) {
            targetTask = taskIndex
                .getTasks()
                .find((task) => isTvInline(task) && task.timerTargetId === timer.timerTargetId);
        }
        if (!targetTask) return;

        if (targetTask.blockId !== timer.timerTargetId) {
            return;
        }

        try {
            await taskIndex.updateTask(targetTask.id, { blockId: undefined });
            await taskIndex.waitForScan(targetTask.file);
        } catch (error) {
            logError(`[TimerWidget] Failed to remove inline timer target ID: ${(error as Error)?.message ?? error}`);
        }
    }

    // ─── Task Resolution ─────────────────────────────────────

    private resolveInlineTaskForTimer(timer: TimerInstance): Task | undefined {
        if (!isTvInline(timer)) return undefined;
        return this.resolver.resolveTvInline(timer);
    }

    private findInlineTaskByTimerTargetId(filePath: string, timerTargetId: string): Task | undefined {
        return this.ctx.plugin
            .getTaskIndex()
            .getTasks()
            .find((task) =>
                isTvInline(task)
                && task.file === filePath
                && (task.timerTargetId === timerTargetId || task.blockId === timerTargetId)
            );
    }
}
