/**
 * Timer Instance Type Definition
 *
 * Shared types for timer instances used by TimerWidget / TimerRecorder / TimerProgressUI.
 */

import type { ParserId } from '../types';

export type TimerPhase = 'idle' | 'work' | 'break' | 'prepare';

/**
 * Identity of a timer instance, stable for its whole life.
 *
 * It must NOT be derived from the task: `handleFileRename` rewrites
 * `timer.taskId` in place, and anything keyed by the old task id (the
 * `timers` map, the widget DOM node, the tick interval) would be stranded.
 * Lookups by task go through a scan instead — the map never holds more than a
 * handful of timers.
 */
export function newTimerId(): string {
    const cryptoObj = globalThis.crypto;
    if (cryptoObj && typeof cryptoObj.randomUUID === 'function') {
        return `timer-${cryptoObj.randomUUID()}`;
    }
    timerIdCounter += 1;
    return `timer-${timerIdCounter}-${Math.floor(Math.random() * 1e9).toString(36)}`;
}

let timerIdCounter = 0;

/**
 * セッションの状態。**ticker が回っているか（{@link TimerBase.isRunning}）とは
 * 別の軸**なので統合しない:
 *
 * - `isRunning` は「今カウントしているか」。interval の prepare フェーズは
 *   ユーザーから見れば一時停止だが `isRunning = true` のまま回るし、開始前
 *   (`phase === 'idle'`, autoStart なし) は `false`
 * - `runState` は「セッションが走行中か、記録済みで再開待ちか」
 *
 * 統合するには 'idle' を足した 3 値が要り、それは `phase` が 'idle' を兼務して
 * いる既存の混乱を持ち込むだけになる。
 *
 * **不変条件: `runState === 'suspended'` ならば `isRunning === false`。**
 * 中断は記録を書き終えた状態なので、ticker が回っていてはならない。
 *
 * countup / countdown の 4 出口でのみ遷移する。interval / idle は常に
 * `'running'`（状態機械の対象外）。
 */
export type TimerRunState = 'running' | 'suspended';

export interface TimerBase {
    id: string;
    taskId: string;
    taskName: string;
    taskOriginalText: string;
    taskFile: string;
    timerTargetId?: string;
    autoGeneratedTargetId?: boolean;
    recordedChildTaskId?: string;

    startTimeMs: number;
    pausedElapsedTime: number;

    phase: TimerPhase;
    isRunning: boolean;
    /** {@link TimerRunState} 参照。isRunning とは別軸。 */
    runState: TimerRunState;
    /** 記録済みセッション数。中断 / 完了のたびに 1 増える。 */
    sessionCount: number;
    /**
     * 記録済みセッションの経過秒の合計。再開時に `pausedElapsedTime` を 0 へ
     * 戻す（セッション = レコード単位）ため、中断中に出す「これまでの合計」は
     * ここからしか作れない。
     */
    recordedElapsedTime: number;
    isExpanded: boolean;
    intervalId: number | null;

    customLabel: string;
    recordMode: 'child' | 'self';
    /** Always a current {@link ParserId}; legacy persisted values are normalized at load. */
    parserId: ParserId;
    taskColor: string;
}

export interface CountupTimer extends TimerBase {
    timerType: 'countup';
    elapsedTime: number;
}

export interface CountdownTimer extends TimerBase {
    timerType: 'countdown';
    timeRemaining: number;
    totalTime: number;
    elapsedTime: number;
}

export interface IntervalSegment {
    label: string;
    durationSeconds: number;
    type: 'work' | 'break' | 'prepare';
}

export interface IntervalGroup {
    segments: IntervalSegment[];
    repeatCount: number;
}

export interface IntervalTimer extends TimerBase {
    timerType: 'interval';
    intervalSource?: 'pomodoro';
    groups: IntervalGroup[];
    currentGroupIndex: number;
    currentSegmentIndex: number;
    currentRepeatIndex: number;
    segmentTimeRemaining: number;
    totalElapsedTime: number;
    totalDuration: number;
}

export interface IdleTimer extends TimerBase {
    timerType: 'idle';
    elapsedTime: number;
}

export type TimerInstance = CountupTimer | CountdownTimer | IntervalTimer | IdleTimer;
export type TimerType = TimerInstance['timerType'];

export interface TimerStartConfig {
    taskId: string;
    taskName: string;
    taskOriginalText?: string;
    taskFile?: string;
    recordMode?: 'child' | 'self';
    parserId?: ParserId;
    timerTargetId?: string;
    taskColor?: string;
    timerType: TimerType | 'pomodoro';
    autoStart?: boolean;
    countdownSeconds?: number;
    intervalGroups?: IntervalGroup[];
    intervalSource?: 'pomodoro';
}

export function getTimerElapsedSeconds(timer: TimerInstance): number {
    switch (timer.timerType) {
        case 'countup':
        case 'countdown':
        case 'idle':
            return timer.elapsedTime;
        case 'interval':
            return timer.totalElapsedTime;
        default:
            return 0;
    }
}
