/**
 * Timer factory — `TimerStartConfig` から走らせる `TimerInstance` を組む。
 *
 * 区間の計算は IntervalMath が持つ（ウィジェットと独立ビューの共有）。ここは
 * 組み立てだけを担う。
 */

import type {
    CountdownTimer,
    CountupTimer,
    IdleTimer,
    IntervalGroup,
    IntervalTimer,
    TimerInstance,
    TimerPhase,
    TimerRunState,
    TimerStartConfig,
} from './TimerInstance';
import { newTimerId } from './TimerInstance';
import { type TimerContext, IDLE_TIMER_ID } from './TimerContext';
import type { TimerStorageUtils } from './TimerStorageUtils';
import { computeTotalDuration, normalizeGroups, type IntervalDefaults } from './IntervalMath';

export class TimerCreator {
    constructor(
        private ctx: TimerContext,
        private storageUtils: TimerStorageUtils,
    ) {}

    // ─── Factory ──────────────────────────────────────────────

    createTimer(config: TimerStartConfig): TimerInstance {
        const autoStart = config.autoStart === true;
        // idle は単一インスタンスの番人なので sentinel id を保つ。それ以外は
        // タスクから独立した不変 id（rename でキーが取り残されないため）。
        const id = config.timerType === 'idle' ? IDLE_TIMER_ID : newTimerId();
        const now = Date.now();
        const base = {
            id,
            taskId: config.timerType === 'idle' ? IDLE_TIMER_ID : config.taskId,
            taskName: config.timerType === 'idle' ? 'Idle' : config.taskName,
            taskOriginalText: config.taskOriginalText ?? '',
            taskFile: config.taskFile ?? '',
            timerTargetId: config.timerType === 'idle' ? undefined : config.timerTargetId,
            autoGeneratedTargetId: config.timerType === 'idle'
                ? false
                : this.storageUtils.isAutoManagedTimerTargetId(config.timerTargetId),
            startTimeMs: autoStart || config.timerType === 'idle' ? now : 0,
            pausedElapsedTime: 0,
            phase: config.timerType === 'idle' ? 'idle' : (autoStart ? 'work' : 'idle') as TimerPhase,
            isRunning: config.timerType === 'idle' ? true : autoStart,
            // 新規タイマーは常に走行側から始まる（中断は既存タイマーの遷移）。
            runState: 'running' as TimerRunState,
            sessionCount: 0,
            recordedElapsedTime: 0,
            isExpanded: true,
            intervalId: null,
            recordMode: config.recordMode ?? 'child',
            parserId: config.parserId ?? 'tv-inline',
            taskColor: config.taskColor ?? ''
        };

        switch (config.timerType) {
            case 'pomodoro': {
                const workSec = this.ctx.plugin.settings.pomodoroWorkMinutes * 60;
                const breakSec = this.ctx.plugin.settings.pomodoroBreakMinutes * 60;
                const groups: IntervalGroup[] = [
                    {
                        segments: [
                            { label: 'Work', durationSeconds: workSec, type: 'work' },
                            { label: 'Break', durationSeconds: breakSec, type: 'break' }
                        ],
                        repeatCount: 0
                    }
                ];
                const timer: IntervalTimer = {
                    ...base,
                    timerType: 'interval',
                    intervalSource: 'pomodoro',
                    groups,
                    currentGroupIndex: 0,
                    currentSegmentIndex: 0,
                    currentRepeatIndex: 0,
                    segmentTimeRemaining: workSec,
                    totalElapsedTime: 0,
                    totalDuration: 0,
                    phase: autoStart ? 'work' : 'idle'
                };
                return timer;
            }
            case 'countup': {
                return {
                    ...base,
                    timerType: 'countup',
                    elapsedTime: 0
                };
            }
            case 'countdown': {
                const total = Math.max(1, Math.floor(config.countdownSeconds ?? this.ctx.plugin.settings.pomodoroWorkMinutes * 60));
                const timer: CountdownTimer = {
                    ...base,
                    timerType: 'countdown',
                    timeRemaining: total,
                    totalTime: total,
                    elapsedTime: 0
                };
                return timer;
            }
            case 'interval': {
                const groups = normalizeGroups(config.intervalGroups, this.intervalDefaults());
                const firstGroup = groups[0];
                const firstSegment = firstGroup.segments[0];
                const timer: IntervalTimer = {
                    ...base,
                    timerType: 'interval',
                    intervalSource: config.intervalSource,
                    groups,
                    currentGroupIndex: 0,
                    currentSegmentIndex: 0,
                    currentRepeatIndex: 0,
                    segmentTimeRemaining: firstSegment.durationSeconds,
                    totalElapsedTime: 0,
                    totalDuration: computeTotalDuration(groups),
                    phase: autoStart ? firstSegment.type : 'idle'
                };
                return timer;
            }
            case 'idle':
            default: {
                const timer: IdleTimer = {
                    ...base,
                    timerType: 'idle',
                    elapsedTime: 0,
                    phase: 'idle',
                    isRunning: true,
                    startTimeMs: now,
                    isExpanded: true
                };
                return timer;
            }
        }
    }

    /**
     * 空のグループ定義に当てる既定。設定は呼ぶたびに読む（起動時に固めると
     * 設定変更が次のタイマーに乗らない）。
     */
    private intervalDefaults(): IntervalDefaults {
        return {
            prepareSeconds: 10,
            workSeconds: this.ctx.plugin.settings.pomodoroWorkMinutes * 60,
            breakSeconds: this.ctx.plugin.settings.pomodoroBreakMinutes * 60,
        };
    }
}
