/**
 * Timer target ID management: cleanup. The anchor is put on at start, in the
 * start write (TimerRecorder.writeStart).
 */

import type { TimerInstance } from './TimerInstance';
import type { TimerContext } from './TimerContext';
import type { TimerStorageUtils } from './TimerStorageUtils';
import { isTvInline } from '../types';
import { logError } from '../log/log';

export class TimerTargetManager {
    constructor(
        private ctx: TimerContext,
        private storageUtils: TimerStorageUtils,
    ) {}

    // ─── Cleanup ─────────────────────────────────────────────

    async cleanupGeneratedTargetId(timer: TimerInstance): Promise<void> {
        if (!timer.autoGeneratedTargetId) return;
        if (!timer.timerTargetId) return;
        if (!this.storageUtils.isAutoManagedTimerTargetId(timer.timerTargetId)) return;
        if (this.hasAnotherActiveTimerWithTarget(timer.timerTargetId)) return;

        if (isTvInline(timer)) {
            await this.removeInlineTimerTargetId(timer, timer.timerTargetId);
        }
    }

    private hasAnotherActiveTimerWithTarget(timerTargetId: string): boolean {
        for (const timer of this.ctx.timers.values()) {
            if (timer.timerTargetId === timerTargetId) {
                return true;
            }
        }
        return false;
    }

    private async removeInlineTimerTargetId(timer: TimerInstance, anchor: string): Promise<void> {
        const taskIndex = this.ctx.plugin.getTaskIndex();
        const targetTask = taskIndex.getTaskByAnchor(timer.taskFile, anchor);
        if (!targetTask) return;

        try {
            await taskIndex.updateTask(targetTask.id, { blockId: undefined });
            await taskIndex.waitForScan(targetTask.file);
        } catch (error) {
            logError(`[TimerWidget] Failed to remove inline timer target ID: ${(error as Error)?.message ?? error}`);
        }
    }
}
