/**
 * Timer Instance Type Definition
 *
 * Shared types for timer instances used by TimerWidget / TimerRecorder / TimerProgressUI.
 */

import type { ParserId } from '../types';

export type TimerPhase = 'idle' | 'work' | 'break' | 'prepare';

/**
 * Identity of a timer instance, stable for its whole life.
 *
 * It must NOT be derived from the task: `handleFileRename` rewrites
 * `timer.taskId` in place, and anything keyed by the old task id (the
 * `timers` map, the widget DOM node, the tick interval) would be stranded.
 * Lookups by task go through a scan instead — the map never holds more than a
 * handful of timers.
 */
export function newTimerId(): string {
    const cryptoObj = globalThis.crypto;
    if (cryptoObj && typeof cryptoObj.randomUUID === 'function') {
        return `timer-${cryptoObj.randomUUID()}`;
    }
    timerIdCounter += 1;
    return `timer-${timerIdCounter}-${Math.floor(Math.random() * 1e9).toString(36)}`;
}

let timerIdCounter = 0;

/**
 * セッションの状態。**ticker が回っているか（{@link TimerBase.isRunning}）とは
 * 別の軸**なので統合しない:
 *
 * - `isRunning` は「今カウントしているか」。interval の prepare フェーズは
 *   ユーザーから見れば一時停止だが `isRunning = true` のまま回るし、開始前
 *   (`phase === 'idle'`, autoStart なし) は `false`
 * - `runState` は「セッションが走行中か、記録済みで再開待ちか」
 *
 * 統合するには 'idle' を足した 3 値が要り、それは `phase` が 'idle' を兼務して
 * いる既存の混乱を持ち込むだけになる。
 *
 * **不変条件: `runState === 'suspended'` ならば `isRunning === false`。**
 * 中断は記録を書き終えた状態なので、ticker が回っていてはならない。
 *
 * countup / countdown の 4 出口でのみ遷移する。interval / idle は常に
 * `'running'`（状態機械の対象外）。
 */
export type TimerRunState = 'running' | 'suspended';

/**
 * **1 本目のセッションをどこに書くか**。2 本目以降は常に直前レコードの兄弟なので、
 * この値が効くのは最初の 1 回だけ。
 *
 * - `self`   … 対象タスク行そのものをレコードに変形する（単発 1 行完結の体験）
 * - `child`  … 対象タスクの子として挿す（器タスク / tvFile / daily）
 * - `sibling`… 対象タスク（完了済み）の兄弟として挿す。`[x]` 起点で「続きを開始」
 *              を選んだときだけ使う
 */
export type TimerRecordMode = 'child' | 'self' | 'sibling';

export interface TimerBase {
    id: string;
    taskId: string;
    taskName: string;
    taskOriginalText: string;
    taskFile: string;
    /** 対象アンカー: ユーザーのタスク行（器 / 起点行）を引き直すための id。 */
    timerTargetId?: string;
    autoGeneratedTargetId?: boolean;
    /**
     * タイマーが**最後に書いたレコード行**の task id（キャッシュ）。走行中なら
     * 走行中の行、中断中なら直前のレコード行を指す。行番号ベースの id なので
     * 編集やリロードで腐る — 正は {@link TimerBase.tailRecordBlockId}。
     */
    recordedChildTaskId?: string;
    /**
     * 尻尾アンカー: 最後に書いたレコード行に付けた `^id`。
     *
     * 対象アンカー（{@link TimerBase.timerTargetId}）とは別物。v1 は両者を 1 本の
     * id で兼ねようとして「対象タスク」と「タイマーが書いたレコード」の区別を
     * 失った。v2 は分けることで「^id は現在の尻尾 1 個」（再開で前の行から外し、
     * widget を閉じたら 0 個）が素直に成立する。
     */
    tailRecordBlockId?: string;
    /**
     * 走行中の行の実効 end（ミリ秒）。これを過ぎるまで end の書き足しを見送る門で、
     * 毎秒の tick がインデックスを引かずに済ませるためだけに持つ。
     *
     * **永続化しない**。復元後は未定義から始まり、最初の tick で走行中の行から
     * 取り直す。行はユーザーにも編集されうるので、記憶した値より現物が正しい。
     */
    lazyEndFloorMs?: number;

    startTimeMs: number;
    pausedElapsedTime: number;

    phase: TimerPhase;
    isRunning: boolean;
    /** {@link TimerRunState} 参照。isRunning とは別軸。 */
    runState: TimerRunState;
    /** 記録済みセッション数。中断 / 完了のたびに 1 増える。 */
    sessionCount: number;
    /**
     * 記録済みセッションの経過秒の合計。再開時に `pausedElapsedTime` を 0 へ
     * 戻す（セッション = レコード単位）ため、中断中に出す「これまでの合計」は
     * ここからしか作れない。
     */
    recordedElapsedTime: number;
    isExpanded: boolean;
    intervalId: number | null;

    customLabel: string;
    recordMode: TimerRecordMode;
    /** Always a current {@link ParserId}; legacy persisted values are normalized at load. */
    parserId: ParserId;
    taskColor: string;
}

export interface CountupTimer extends TimerBase {
    timerType: 'countup';
    elapsedTime: number;
}

export interface CountdownTimer extends TimerBase {
    timerType: 'countdown';
    timeRemaining: number;
    totalTime: number;
    elapsedTime: number;
}

export interface IntervalSegment {
    label: string;
    durationSeconds: number;
    type: 'work' | 'break' | 'prepare';
}

export interface IntervalGroup {
    segments: IntervalSegment[];
    repeatCount: number;
}

export interface IntervalTimer extends TimerBase {
    timerType: 'interval';
    intervalSource?: 'pomodoro';
    groups: IntervalGroup[];
    currentGroupIndex: number;
    currentSegmentIndex: number;
    currentRepeatIndex: number;
    segmentTimeRemaining: number;
    totalElapsedTime: number;
    totalDuration: number;
}

export interface IdleTimer extends TimerBase {
    timerType: 'idle';
    elapsedTime: number;
}

export type TimerInstance = CountupTimer | CountdownTimer | IntervalTimer | IdleTimer;
export type TimerType = TimerInstance['timerType'];

export interface TimerStartConfig {
    taskId: string;
    taskName: string;
    taskOriginalText?: string;
    taskFile?: string;
    recordMode?: TimerRecordMode;
    parserId?: ParserId;
    timerTargetId?: string;
    taskColor?: string;
    timerType: TimerType | 'pomodoro';
    autoStart?: boolean;
    countdownSeconds?: number;
    intervalGroups?: IntervalGroup[];
    intervalSource?: 'pomodoro';
}

export function getTimerElapsedSeconds(timer: TimerInstance): number {
    switch (timer.timerType) {
        case 'countup':
        case 'countdown':
        case 'idle':
            return timer.elapsedTime;
        case 'interval':
            return timer.totalElapsedTime;
        default:
            return 0;
    }
}
