/**
 * Timer persistence: serialize, deserialize, migrate, reconcile.
 */

import type { ParserId } from '../types';
import type {
    IntervalGroup,
    IntervalTimer,
    TimerInstance,
    TimerPhase,
    TimerRecordMode,
    TimerRunState,
    TimerType,
} from './TimerInstance';
import { isDailyTimer } from './TimerInstance';
import type { TimerContext } from './TimerContext';
import { OBSOLETE_STORAGE_VERSIONS, STORAGE_VERSION } from './TimerStorageUtils';
import type { TimerCreator } from './TimerCreator';
import {
    clampToTotalDuration,
    computeCompletedDuration,
    computeTotalDuration,
    getCurrentSegment,
    normalizeGroups,
    type IntervalDefaults,
} from './IntervalMath';
import type { TimerLifecycle } from './TimerLifecycle';
import type { TimerStorageUtils } from './TimerStorageUtils';
import { TaskIdGenerator } from '../services/display/TaskIdGenerator';
import { TimerTaskResolver } from './TimerTaskResolver';
import { isTvFile } from '../types';
import { Notice } from 'obsidian';
import { t } from '../i18n';
import { logError, logInfo } from '../log/log';

/**
 * Map legacy parserId values (pre-rename) to current ones. Persisted timer
 * state may contain old strings from earlier plugin versions; normalize on
 * read so downstream code can rely on the current vocabulary.
 *
 * Migration is one-way and idempotent — once read and re-saved, persisted
 * data uses the new values. Safe to remove this table after a few releases.
 */
const PARSER_ID_MIGRATION: Record<string, ParserId> = {
    'at-notation': 'tv-inline',
    'frontmatter': 'tv-file',
    'plain': 'tv-inline',
};

const CURRENT_PARSER_IDS: ReadonlySet<ParserId> = new Set(['tv-inline', 'tv-file', 'tasks-plugin', 'day-planner']);

function normalizeParserId(value: string | undefined): ParserId {
    if (!value) return 'tv-inline';
    const migrated = PARSER_ID_MIGRATION[value];
    if (migrated) return migrated;
    return CURRENT_PARSER_IDS.has(value as ParserId) ? (value as ParserId) : 'tv-inline';
}

export interface PersistedTimer {
    id: string;
    taskId: string;
    taskName: string;
    taskOriginalText: string;
    taskFile: string;
    timerTargetId?: string;
    autoGeneratedTargetId?: boolean;
    recordedChildTaskId?: string;
    tailRecordBlockId?: string;
    startTimeMs: number;
    pausedElapsedTime: number;
    phase?: TimerPhase;
    isRunning: boolean;
    runState?: TimerRunState;
    sessionCount?: number;
    recordedElapsedTime?: number;
    isExpanded: boolean;
    pendingContent?: string;
    /** v0.51.0 以前の下書き。読むときだけ拾う（書き出しは pendingContent）。 */
    customLabel?: string;
    /**
     * 保存するのは実行時の種別だけ。`TimerStartConfig` の `'pomodoro'` は
     * 開始時の便宜値で、`TimerInstance` になった時点で `interval` に化けている。
     */
    timerType: TimerType;
    recordMode: TimerRecordMode;
    parserId: string;
    taskColor?: string;

    timeRemaining?: number;
    totalTime?: number;
    elapsedTime?: number;

    groups?: IntervalGroup[];
    currentGroupIndex?: number;
    currentSegmentIndex?: number;
    currentRepeatIndex?: number;
    segmentTimeRemaining?: number;
    totalElapsedTime?: number;
    totalDuration?: number;
    intervalSource?: 'pomodoro';
}

export interface PersistedTimerState {
    version: number;
    ownerDeviceId: string;
    vaultFingerprint: string;
    updatedAtMs: number;
    timers: PersistedTimer[];
}

export class TimerPersistence {
    constructor(
        private ctx: TimerContext,
        private creator: TimerCreator,
        private lifecycle: TimerLifecycle,
        private storageUtils: TimerStorageUtils,
    ) {}

    // ─── Persist ─────────────────────────────────────────────

    persistTimersToStorage(): void {
        logInfo(`[Timer:persist] count=${this.ctx.timers.size}`);
        const storageKey = this.storageUtils.getStorageKey();
        try {
            if (this.ctx.timers.size === 0) {
                window.localStorage.removeItem(storageKey);
                return;
            }

            const payload: PersistedTimerState = {
                version: STORAGE_VERSION,
                ownerDeviceId: this.storageUtils.deviceId,
                vaultFingerprint: this.storageUtils.vaultFingerprint,
                updatedAtMs: Date.now(),
                timers: Array.from(this.ctx.timers.values()).map((timer) => this.toPersistedTimer(timer))
            };

            window.localStorage.setItem(storageKey, JSON.stringify(payload));
        } catch (error) {
            logError(`[TimerWidget] Failed to persist timers: ${(error as Error)?.message ?? error}`);
        }
    }

    // ─── Restore ─────────────────────────────────────────────

    restoreTimersFromStorage(onTimerRestored?: (timerId: string) => void): void {
        const storageKey = this.storageUtils.getStorageKey();
        this.dropObsoleteStorage();
        try {
            const raw = window.localStorage.getItem(storageKey);
            if (!raw) return;

            const parsed = JSON.parse(raw) as PersistedTimerState;

            if (
                !parsed
                || parsed.version !== STORAGE_VERSION
                || parsed.vaultFingerprint !== this.storageUtils.vaultFingerprint
                || !Array.isArray(parsed.timers)
            ) {
                window.localStorage.removeItem(storageKey);
                return;
            }
            if (parsed.ownerDeviceId !== this.storageUtils.deviceId) {
                return;
            }

            for (const persisted of parsed.timers) {
                const timer = this.fromPersistedTimer(persisted);
                if (!timer) continue;

                this.reconcileRestoredTimer(timer);
                this.ctx.timers.set(timer.id, timer);
            }

            if (this.ctx.timers.size === 0) {
                this.persistTimersToStorage();
                return;
            }

            for (const [timerId, timer] of this.ctx.timers) {
                if (timer.isRunning) {
                    if (timer.timerType === 'interval' && timer.segmentTimeRemaining <= 0) {
                        void this.lifecycle.handleIntervalSegmentComplete(timerId, timer);
                    } else {
                        this.lifecycle.startTimerTicker(timerId);
                    }
                }

                if (onTimerRestored) {
                    onTimerRestored(timerId);
                }
            }

            logInfo(`[Timer:restored] count=${this.ctx.timers.size}`);
            this.ctx.render();
            this.scheduleAnchorVerification();
        } catch (error) {
            window.localStorage.removeItem(storageKey);
            logError(`[TimerWidget] Failed to restore timers: ${(error as Error)?.message ?? error}`);
        }
    }

    /**
     * 復元したタイマーのアンカー先タスクがまだ存在するかを、**最初の onChange
     * を待ってから**検証する。
     *
     * 復元は layout-ready 直後に走るので、その時点では初回スキャンが終わって
     * おらず index は空でありうる。そこで判定すると生きているタイマーを全部
     * 壊す。`waitForScan` はキュー済みのスキャンしか待たないので当てにならず、
     * 「最初の変更通知が来た ＝ スキャンがタスクを流し始めた」を合図にする。
     * 通知が来なければ何も壊さない（保守的側に倒す）。
     */
    private scheduleAnchorVerification(): void {
        const readService = this.ctx.plugin.getTaskReadService();
        let done = false;
        const unsubscribe = readService.onChange(() => {
            if (done) return;
            done = true;
            unsubscribe();
            this.dropTimersWithMissingAnchor();
        });
    }

    private dropTimersWithMissingAnchor(): void {
        const resolver = new TimerTaskResolver(this.ctx.plugin);
        for (const [timerId, timer] of [...this.ctx.timers]) {
            if (this.lifecycle.isIdleTimer(timerId)) continue;
            // デイリーノート起点は対象タスクを持たない。引けないのが正常なので、
            // ここで閉じると復元のたびに生きているタイマーを壊す。
            if (isDailyTimer(timer)) continue;

            const task = isTvFile(timer) ? resolver.resolveTvFile(timer) : resolver.resolveTvInline(timer);
            if (task) continue;

            logInfo(`[Timer:anchorMissing] timerId=${timerId} taskId=${timer.taskId}`);
            new Notice(t('notice.timerTargetNotFound'));
            this.lifecycle.closeTimer(timerId);
        }
    }

    /**
     * 旧バージョンのキーを掃除する。ストレージキーはバージョン込みなので古い
     * 状態が読まれることはないが、消さないと localStorage に残り続ける。
     */
    private dropObsoleteStorage(): void {
        for (const version of OBSOLETE_STORAGE_VERSIONS) {
            try {
                window.localStorage.removeItem(this.storageUtils.getStorageKeyForVersion(version));
            } catch {
                // localStorage が使えない環境では黙って諦める（復元も同様に失敗する）
            }
        }
    }

    // ─── Serialization ───────────────────────────────────────

    private toPersistedTimer(timer: TimerInstance): PersistedTimer {
        const common: PersistedTimer = {
            id: timer.id,
            taskId: timer.taskId,
            taskName: timer.taskName,
            taskOriginalText: timer.taskOriginalText,
            taskFile: timer.taskFile,
            timerTargetId: timer.timerTargetId,
            autoGeneratedTargetId: timer.autoGeneratedTargetId,
            recordedChildTaskId: timer.recordedChildTaskId,
            tailRecordBlockId: timer.tailRecordBlockId,
            startTimeMs: timer.startTimeMs,
            pausedElapsedTime: timer.pausedElapsedTime,
            phase: timer.phase,
            isRunning: timer.isRunning,
            runState: timer.runState,
            sessionCount: timer.sessionCount,
            recordedElapsedTime: timer.recordedElapsedTime,
            isExpanded: timer.isExpanded,
            pendingContent: timer.pendingContent,
            timerType: timer.timerType,
            recordMode: timer.recordMode,
            parserId: timer.parserId,
            taskColor: timer.taskColor
        };

        switch (timer.timerType) {
            case 'countup':
                return {
                    ...common,
                    elapsedTime: timer.elapsedTime
                };
            case 'countdown':
                return {
                    ...common,
                    timeRemaining: timer.timeRemaining,
                    totalTime: timer.totalTime,
                    elapsedTime: timer.elapsedTime
                };
            case 'interval':
                return {
                    ...common,
                    groups: timer.groups,
                    currentGroupIndex: timer.currentGroupIndex,
                    currentSegmentIndex: timer.currentSegmentIndex,
                    currentRepeatIndex: timer.currentRepeatIndex,
                    segmentTimeRemaining: timer.segmentTimeRemaining,
                    totalElapsedTime: timer.totalElapsedTime,
                    totalDuration: timer.totalDuration,
                    intervalSource: timer.intervalSource
                };
            case 'idle':
            default:
                return {
                    ...common,
                    elapsedTime: timer.elapsedTime
                };
        }
    }

    private fromPersistedTimer(persisted: PersistedTimer): TimerInstance | null {
        if (!persisted || !persisted.id || !persisted.taskId) {
            return null;
        }

        const taskId = persisted.taskId;
        if (!this.lifecycle.isIdleTimer(taskId) && !isDailyTimer({ taskId }) && !TaskIdGenerator.parse(taskId)) {
            return null;
        }

        const phase = (persisted.phase ?? 'idle') as TimerPhase;
        const common = {
            id: persisted.id,
            taskId,
            taskName: persisted.taskName || 'Untitled',
            taskOriginalText: persisted.taskOriginalText || '',
            taskFile: persisted.taskFile || '',
            timerTargetId: persisted.timerTargetId,
            autoGeneratedTargetId: persisted.autoGeneratedTargetId ?? this.storageUtils.isAutoManagedTimerTargetId(persisted.timerTargetId),
            recordedChildTaskId: persisted.recordedChildTaskId,
            // v2 より前の状態には無い。undefined なら尻尾は task id / 対象
            // アンカーから引き直す（TimerRecorder.resolveTailRecord）。
            tailRecordBlockId: persisted.tailRecordBlockId,
            startTimeMs: persisted.startTimeMs || 0,
            pausedElapsedTime: persisted.pausedElapsedTime || 0,
            phase,
            isRunning: !!persisted.isRunning,
            // 不変条件: suspended なら ticker は止まっている。
            runState: (persisted.runState === 'suspended' ? 'suspended' : 'running') as TimerRunState,
            sessionCount: persisted.sessionCount ?? 0,
            recordedElapsedTime: persisted.recordedElapsedTime ?? 0,
            isExpanded: persisted.isExpanded !== false,
            intervalId: null,
            // v0.51.0 以前の customLabel は下書きとして引き継ぐ。書き先の行がある
            // なら次の書き出しで消える。
            pendingContent: persisted.pendingContent ?? persisted.customLabel ?? undefined,
            recordMode: persisted.recordMode || 'child',
            parserId: normalizeParserId(persisted.parserId),
            taskColor: persisted.taskColor || ''
        };

        switch (persisted.timerType) {
            case 'countdown': {
                const totalTime = Math.max(1, persisted.totalTime ?? this.ctx.plugin.settings.pomodoroWorkMinutes * 60);
                const elapsedTime = Math.max(0, persisted.elapsedTime ?? persisted.pausedElapsedTime ?? 0);
                const timeRemaining = persisted.timeRemaining ?? (totalTime - elapsedTime);
                return {
                    ...common,
                    timerType: 'countdown',
                    timeRemaining,
                    totalTime,
                    elapsedTime
                };
            }
            case 'interval': {
                const groups = normalizeGroups(persisted.groups, this.intervalDefaults());
                const intervalTimer: IntervalTimer = {
                    ...common,
                    timerType: 'interval',
                    intervalSource: persisted.intervalSource,
                    groups,
                    currentGroupIndex: Math.max(0, persisted.currentGroupIndex ?? 0),
                    currentSegmentIndex: Math.max(0, persisted.currentSegmentIndex ?? 0),
                    currentRepeatIndex: Math.max(0, persisted.currentRepeatIndex ?? 0),
                    segmentTimeRemaining: Math.max(0, persisted.segmentTimeRemaining ?? groups[0].segments[0].durationSeconds),
                    totalElapsedTime: Math.max(0, persisted.totalElapsedTime ?? 0),
                    totalDuration: Math.max(0, persisted.totalDuration ?? computeTotalDuration(groups))
                };
                const segment = getCurrentSegment(intervalTimer);
                if (!segment) {
                    return null;
                }
                if (intervalTimer.segmentTimeRemaining <= 0) {
                    intervalTimer.segmentTimeRemaining = segment.durationSeconds;
                }
                return intervalTimer;
            }
            case 'idle': {
                return {
                    ...common,
                    timerType: 'idle',
                    elapsedTime: Math.max(0, persisted.elapsedTime ?? persisted.pausedElapsedTime ?? 0),
                    phase: 'idle'
                };
            }
            case 'countup':
            default: {
                return {
                    ...common,
                    timerType: 'countup',
                    elapsedTime: Math.max(0, persisted.elapsedTime ?? persisted.pausedElapsedTime ?? 0)
                };
            }
        }
    }

    // ─── Reconciliation ──────────────────────────────────────

    private reconcileRestoredTimer(timer: TimerInstance): void {
        if (timer.runState === 'suspended') {
            // 中断中 = 記録済み・再開待ち。閉じていた間の時間は次のセッションに
            // 属さないので経過を積まない。表示は recordedElapsedTime の静的値。
            timer.isRunning = false;
            timer.startTimeMs = 0;
            timer.pausedElapsedTime = 0;
            if (timer.timerType === 'countup' || timer.timerType === 'idle') {
                timer.elapsedTime = 0;
            } else if (timer.timerType === 'countdown') {
                timer.elapsedTime = 0;
                timer.timeRemaining = timer.totalTime;
                timer.phase = 'work';
            }
            return;
        }

        if (!timer.isRunning) {
            if (timer.timerType === 'countup' || timer.timerType === 'idle') {
                timer.elapsedTime = Math.max(timer.elapsedTime, timer.pausedElapsedTime);
            } else if (timer.timerType === 'countdown') {
                timer.elapsedTime = Math.max(timer.elapsedTime, timer.pausedElapsedTime);
                timer.timeRemaining = timer.totalTime - timer.elapsedTime;
                timer.phase = timer.timeRemaining < 0 ? 'idle' : 'work';
            } else if (timer.timerType === 'interval') {
                const segment = getCurrentSegment(timer);
                if (segment) {
                    timer.segmentTimeRemaining = Math.max(0, segment.durationSeconds - timer.pausedElapsedTime);
                    timer.totalElapsedTime = clampToTotalDuration(
                        timer.totalDuration,
                        computeCompletedDuration(timer) + Math.min(segment.durationSeconds, timer.pausedElapsedTime)
                    );
                }
            }
            return;
        }

        if (timer.startTimeMs <= 0) {
            timer.startTimeMs = Date.now();
        }

        const now = Date.now();
        const currentSessionElapsed = Math.floor((now - timer.startTimeMs) / 1000);
        const totalElapsed = Math.max(0, timer.pausedElapsedTime + currentSessionElapsed);

        switch (timer.timerType) {
            case 'countup':
            case 'idle':
                timer.elapsedTime = totalElapsed;
                break;
            case 'countdown':
                timer.elapsedTime = totalElapsed;
                timer.timeRemaining = timer.totalTime - totalElapsed;
                timer.phase = timer.timeRemaining < 0 ? 'idle' : 'work';
                break;
            case 'interval': {
                const segment = getCurrentSegment(timer);
                if (!segment) {
                    timer.segmentTimeRemaining = 0;
                    timer.totalElapsedTime = timer.totalDuration;
                    break;
                }
                timer.segmentTimeRemaining = Math.max(0, segment.durationSeconds - totalElapsed);
                timer.totalElapsedTime = clampToTotalDuration(
                    timer.totalDuration,
                    computeCompletedDuration(timer) + Math.min(segment.durationSeconds, totalElapsed)
                );
                break;
            }
            default:
                break;
        }
    }

    /** 空の永続グループに当てる既定。{@link TimerCreator} と同じ設定を読む。 */
    private intervalDefaults(): IntervalDefaults {
        return {
            prepareSeconds: 10,
            workSeconds: this.ctx.plugin.settings.pomodoroWorkMinutes * 60,
            breakSeconds: this.ctx.plugin.settings.pomodoroBreakMinutes * 60,
        };
    }
}
