import { describe, it, expect } from 'vitest';
import type { Task } from '../../src/types';
import { makeTask } from '../helpers/makeTask';

// ---------------------------------------------------------------------------
// Issue 1: TimerMenuBuilder guard — completed command tasks must not show Track Self
// ---------------------------------------------------------------------------

/**
 * Extracted guard logic from TimerMenuBuilder.addTimerSubmenu().
 * Returns true if the Track Self menu should be suppressed.
 */
function shouldSuppressTrackSelf(task: Task): boolean {
    return task.statusChar !== ' ' && !!task.commands && task.commands.length > 0;
}

describe('TimerMenuBuilder guard: completed command task suppression', () => {
    it('完了済みコマンドタスクに Track Self メニューを表示しない', () => {
        const task = makeTask({
            statusChar: 'x',
            commands: [{ name: 'repeat', args: ['1days'], modifiers: [] }],
        });
        expect(shouldSuppressTrackSelf(task)).toBe(true);
    });

    it('未完了コマンドタスクでは Track Self を許可する', () => {
        const task = makeTask({
            statusChar: ' ',
            commands: [{ name: 'repeat', args: ['1days'], modifiers: [] }],
        });
        expect(shouldSuppressTrackSelf(task)).toBe(false);
    });

    it('完了済みだがコマンドなしタスクでは Track Self を許可する', () => {
        const task = makeTask({
            statusChar: 'x',
            commands: [],
        });
        expect(shouldSuppressTrackSelf(task)).toBe(false);
    });

    it('未完了でコマンドなしタスクでは Track Self を許可する', () => {
        const task = makeTask({
            statusChar: ' ',
            commands: [],
        });
        expect(shouldSuppressTrackSelf(task)).toBe(false);
    });
});

// ---------------------------------------------------------------------------
// Issue 2: blockId handling in updateTaskDirectly
// ---------------------------------------------------------------------------

/**
 * Extracted blockId resolution logic from TimerRecorder.updateTaskDirectly().
 * Determines the blockId value to write when completing a self-mode timer.
 */
function resolveBlockIdForUpdate(
    autoGeneratedTargetId: boolean | undefined,
    existingBlockId: string | undefined
): string | undefined {
    return autoGeneratedTargetId ? undefined : existingBlockId;
}

describe('updateTaskDirectly blockId handling', () => {
    it('autoGeneratedTargetId=true のとき blockId をクリアする', () => {
        const result = resolveBlockIdForUpdate(true, 'tv-timer-target-abc123');
        expect(result).toBeUndefined();
    });

    it('autoGeneratedTargetId=false のとき既存 blockId を保持する', () => {
        const result = resolveBlockIdForUpdate(false, 'my-reference');
        expect(result).toBe('my-reference');
    });

    it('autoGeneratedTargetId=undefined のとき既存 blockId を保持する', () => {
        const result = resolveBlockIdForUpdate(undefined, 'user-block');
        expect(result).toBe('user-block');
    });

    it('autoGeneratedTargetId=false で blockId が undefined のときも undefined を返す', () => {
        const result = resolveBlockIdForUpdate(false, undefined);
        expect(result).toBeUndefined();
    });
});
