import { describe, expect, it, beforeEach } from 'vitest';
import { Notice } from 'obsidian';
import { TimerCreator } from '../../../src/timer/TimerCreator';
import { TimerLifecycle } from '../../../src/timer/TimerLifecycle';
import { TimerPersistence } from '../../../src/timer/TimerPersistence';
import { STORAGE_VERSION } from '../../../src/timer/TimerStorageUtils';
import type { TimerStorageUtils } from '../../../src/timer/TimerStorageUtils';
import { IDLE_TIMER_ID, type TimerContext } from '../../../src/timer/TimerContext';
import type { TimerInstance } from '../../../src/timer/TimerInstance';

/**
 * A timer persisted while it ran on a file task, restored after the upgrade.
 *
 * Frontmatter makes no task any more, so there is nothing for such a timer to
 * record onto. It must not linger as a ghost, and it must not vanish silently
 * either: the anchor check closes it with exactly one notice. Its parser falls
 * back to `tv-inline` (neither `tv-file` nor the older `frontmatter` is a parser
 * a timer may name), the inline resolver finds nothing for an `fm-root` ID, and
 * dropTimersWithMissingAnchor does the rest.
 */

const store = new Map<string, string>();
(globalThis as unknown as { window: unknown }).window = {
    localStorage: {
        getItem: (k: string) => (store.has(k) ? store.get(k)! : null),
        setItem: (k: string, v: string) => { store.set(k, v); },
        removeItem: (k: string) => { store.delete(k); },
    },
    setInterval: () => 1,
    clearInterval: () => { /* unused */ },
};

const VAULT = 'vault-fp';
const DEVICE = 'device-1';
const keyFor = (version: number) => `task-viewer.active-timers.v${version}:${VAULT}`;

const storageUtils = {
    deviceId: DEVICE,
    vaultFingerprint: VAULT,
    getStorageKey: () => keyFor(STORAGE_VERSION),
    getStorageKeyForVersion: (v: number) => keyFor(v),
    isAutoManagedTimerTargetId: () => true,
} as unknown as TimerStorageUtils;

function build() {
    let fireChange: () => void = () => { throw new Error('no onChange subscriber'); };
    const closed: string[] = [];
    const plugin = {
        settings: { pomodoroWorkMinutes: 25, pomodoroBreakMinutes: 5 },
        getTaskReadService: () => ({
            onChange: (cb: () => void) => { fireChange = cb; return () => { /* unsubscribed */ }; },
        }),
        // The scan has run: the note's checkboxes are there, the file task is not.
        getTaskIndex: () => ({ getTasks: () => [], getTask: () => undefined, getTaskByAnchor: () => undefined }),
    } as unknown as TimerContext['plugin'];
    const ctx = {
        timers: new Map<string, TimerInstance>(),
        recorder: {
            resolveTarget: (timer: TimerInstance) => {
                const index = plugin.getTaskIndex();
                return timer.timerTargetId ? index.getTaskByAnchor(timer.taskFile, timer.timerTargetId) : index.getTask(timer.taskId);
            },
        } as unknown as TimerContext['recorder'],
        plugin,
        app: {} as TimerContext['app'],
        startTimer: () => { /* unused */ },
        render: () => { /* unused */ },
        renderTimerItem: () => { /* unused */ },
        persistTimersToStorage: () => { /* unused */ },
        onTimerClosed: (timer: TimerInstance) => { closed.push(timer.id); },
        flushTimerContent: async () => { /* unused */ },
        discardTimerContent: () => { /* unused */ },
        ensureContainer: () => ({}) as HTMLElement,
        destroyContainer: () => { /* unused */ },
        getPinState: () => 'pinned' as const,
        togglePin: () => { /* unused */ },
        shouldShowPinBadge: () => false,
    } as unknown as TimerContext;
    const creator = new TimerCreator(ctx, storageUtils);
    const lifecycle = new TimerLifecycle(ctx, creator);
    const persistence = new TimerPersistence(ctx, creator, lifecycle, storageUtils);
    return { ctx, persistence, closed, fireChange: () => fireChange() };
}

function persistFileTaskTimer(parserId: string): void {
    store.set(keyFor(STORAGE_VERSION), JSON.stringify({
        version: STORAGE_VERSION,
        ownerDeviceId: DEVICE,
        vaultFingerprint: VAULT,
        updatedAtMs: Date.now(),
        timers: [{
            id: 'timer-fm',
            taskId: 'tv-file:projects/alpha.md:fm-root',
            taskName: 'alpha',
            taskOriginalText: '',
            taskFile: 'projects/alpha.md',
            timerTargetId: 'tv-t-legacy',
            autoGeneratedTargetId: true,
            startTimeMs: Date.now() - 60_000,
            pausedElapsedTime: 0,
            isRunning: true,
            isExpanded: true,
            timerType: 'countup',
            recordMode: 'self',
            parserId,
            elapsedTime: 60,
        }],
    }));
}

describe('a timer that ran on a file task, restored after the upgrade', () => {
    beforeEach(() => {
        store.clear();
        Notice.messages.length = 0;
    });

    it.each(['tv-file', 'frontmatter'])('is closed with exactly one notice (persisted parserId %s)', (parserId) => {
        persistFileTaskTimer(parserId);
        const { ctx, persistence, closed, fireChange } = build();

        persistence.restoreTimersFromStorage();
        const restored = ctx.timers.get('timer-fm');
        expect(restored).toBeDefined();
        expect(restored!.parserId).toBe('tv-inline');

        fireChange();

        expect(ctx.timers.has('timer-fm')).toBe(false);
        expect(closed).toEqual(['timer-fm']);
        expect(Notice.messages).toHaveLength(1);
        expect([...ctx.timers.keys()]).toEqual([IDLE_TIMER_ID]);
    });
});
