import { describe, expect, it, vi } from 'vitest';
import type { App } from 'obsidian';
import { TimerRecorder } from '../../../src/timer/TimerRecorder';
import { TimerTargetManager } from '../../../src/timer/TimerTargetManager';
import type { TimerInstance } from '../../../src/timer/TimerInstance';
import type { TimerContext } from '../../../src/timer/TimerContext';
import type { TimerStorageUtils } from '../../../src/timer/TimerStorageUtils';
import type TaskViewerPlugin from '../../../src/main';
import { makeTask } from '../helpers/makeTask';

/**
 * The timer's `^id` anchor follows what the file holds. An id the write did not
 * add is not on the line, so the timer does not take it as its anchor; an id
 * the write did not remove is still on the line, so the timer does not let go
 * of it. (The reason a write was not made is told by the write layer.)
 */

const FILE = 'notes/a.md';
const TARGET_ID = 'tv-inline:notes/a.md:ln:3';
const TAIL_ID = 'tv-inline:notes/a.md:ln:5';
const ANCHOR = 'tv-t-anchor';

function makeTimer(overrides: Partial<TimerInstance> = {}): TimerInstance {
    return {
        id: 'timer-1',
        taskId: TARGET_ID,
        taskName: 'target',
        taskOriginalText: '- [ ] target',
        taskFile: FILE,
        startTimeMs: 0,
        pausedElapsedTime: 0,
        phase: 'work',
        isRunning: true,
        runState: 'running',
        sessionCount: 0,
        recordedElapsedTime: 0,
        isExpanded: true,
        intervalId: null,
        recordMode: 'child',
        parserId: 'tv-inline',
        taskColor: '',
        timerType: 'countup',
        elapsedTime: 0,
        ...overrides,
    } as TimerInstance;
}

describe('TimerRecorder: taking the tail `^id` off', () => {
    function harness(updateResult: boolean) {
        // The tail line carries the timer's own anchor: the self-mode first record.
        const tail = makeTask({ id: TAIL_ID, file: FILE, line: 5, content: 'record', blockId: ANCHOR, statusChar: 'x', endTime: '10:00' });
        const updateTask = vi.fn(async () => updateResult);
        const waitForScan = vi.fn(async () => { /* the scan is done */ });
        const taskIndex = {
            getTasks: () => [tail],
            getTask: (id: string) => (id === TAIL_ID ? tail : undefined),
            updateTask,
            waitForScan,
            deleteTask: vi.fn(async () => true),
        };
        const plugin = { settings: {}, getTaskIndex: () => taskIndex } as unknown as TaskViewerPlugin;
        const recorder = new TimerRecorder({} as App, plugin, {} as TimerStorageUtils);
        recorder.resolveTailRecord = () => tail;
        const timer = makeTimer({
            tailRecordBlockId: ANCHOR,
            timerTargetId: ANCHOR,
            autoGeneratedTargetId: true,
        });
        return { recorder, timer, updateTask };
    }

    it.each([
        ['clearTailRecordId', (r: TimerRecorder, t: TimerInstance) => r.clearTailRecordId(t)],
        ['discardRunningPlaceholder', (r: TimerRecorder, t: TimerInstance) => r.discardRunningPlaceholder(t)],
    ] as const)('%s: keeps the anchor when the id was not taken off', async (_name, act) => {
        const h = harness(false);

        await act(h.recorder, h.timer);

        expect(h.updateTask).toHaveBeenCalledWith(TAIL_ID, { blockId: undefined });
        expect(h.timer.timerTargetId).toBe(ANCHOR);
        expect(h.timer.autoGeneratedTargetId).toBe(true);
    });

    it.each([
        ['clearTailRecordId', (r: TimerRecorder, t: TimerInstance) => r.clearTailRecordId(t)],
        ['discardRunningPlaceholder', (r: TimerRecorder, t: TimerInstance) => r.discardRunningPlaceholder(t)],
    ] as const)('%s: lets go of the anchor when the id was taken off', async (_name, act) => {
        const h = harness(true);

        await act(h.recorder, h.timer);

        expect(h.updateTask).toHaveBeenCalledWith(TAIL_ID, { blockId: undefined });
        expect(h.timer.timerTargetId).toBeUndefined();
        expect(h.timer.autoGeneratedTargetId).toBe(false);
    });
});

describe('TimerTargetManager: putting the target `^id` on', () => {
    const NEW_ID = 'tv-t-new';

    function harness(updateResult: boolean) {
        let target = makeTask({ id: TARGET_ID, file: FILE, line: 3, content: 'target', originalText: '- [ ] target' });
        const updateTask = vi.fn(async (_id: string, u: { blockId?: string }) => {
            // A write that lands is on the line, as the next scan reads it.
            if (updateResult) target = { ...target, blockId: u.blockId, originalText: `- [ ] target ^${u.blockId}` };
            return updateResult;
        });
        const waitForScan = vi.fn(async () => { /* the scan is done */ });
        const taskIndex = { getTasks: () => [target], updateTask, waitForScan };
        const persist = vi.fn();
        const timer = makeTimer();
        const ctx = {
            timers: new Map([[timer.id, timer]]),
            plugin: { getTaskIndex: () => taskIndex },
            persistTimersToStorage: persist,
        } as unknown as TimerContext;
        const storageUtils = {
            generateTimerTargetId: () => NEW_ID,
            isAutoManagedTimerTargetId: (id: string) => id.startsWith('tv-t-'),
        } as unknown as TimerStorageUtils;
        const manager = new TimerTargetManager(ctx, storageUtils);
        (manager as unknown as { resolver: unknown }).resolver = { resolveTvInline: () => target };
        return { manager, timer, updateTask, waitForScan, persist };
    }

    it('takes no anchor, waits for no scan and persists nothing when the id was not put on', async () => {
        const h = harness(false);
        const before = { taskId: h.timer.taskId, taskOriginalText: h.timer.taskOriginalText };

        await h.manager.ensureTimerTargetId(h.timer.id);

        expect(h.updateTask).toHaveBeenCalledWith(TARGET_ID, { blockId: NEW_ID });
        expect(h.waitForScan).not.toHaveBeenCalled();
        expect(h.timer.taskId).toBe(before.taskId);
        expect(h.timer.taskOriginalText).toBe(before.taskOriginalText);
        expect(h.timer.timerTargetId).toBeUndefined();
        expect(h.timer.autoGeneratedTargetId).toBeUndefined();
        expect(h.persist).not.toHaveBeenCalled();
    });

    it('takes the new id as its anchor when it was put on', async () => {
        const h = harness(true);

        await h.manager.ensureTimerTargetId(h.timer.id);

        expect(h.waitForScan).toHaveBeenCalledWith(FILE);
        expect(h.timer.taskId).toBe(TARGET_ID);
        expect(h.timer.taskOriginalText).toBe(`- [ ] target ^${NEW_ID}`);
        expect(h.timer.timerTargetId).toBe(NEW_ID);
        expect(h.timer.autoGeneratedTargetId).toBe(true);
        expect(h.persist).toHaveBeenCalledTimes(1);
    });
});
