import { describe, it, expect, afterEach, vi } from 'vitest';
import { Notice } from 'obsidian';
import type { TimerInstance, TimerRecordMode } from '../../../src/timer/TimerInstance';
import { vaultSession, type VaultSession } from '../helpers/vaultSession';

/**
 * A timer runs on its target's anchor: the start write puts a `^id` on the
 * target row when it has none, in the one write that starts the timer (the
 * start time on the row for self, the first session line for child and
 * sibling). A row whose `^id` another row carries too cannot be anchored, and
 * the timer does not start.
 */

const FILE = 'notes/a.md';

afterEach(() => vi.useRealTimers());

function lines(contents: Map<string, string>): string[] {
    return contents.get(FILE)!.split('\n').filter(line => line.trim() !== '');
}

async function timerOn(s: VaultSession, mode: TimerRecordMode, content = '対象'): Promise<TimerInstance> {
    await s.scanAll();
    const target = s.index.getTasks().find(task => task.content === content)!;
    return s.creator.createTimer({
        taskId: target.id, taskName: target.content, taskFile: target.file, taskOriginalText: target.originalText,
        timerTargetId: target.anchor, timerType: 'countup', recordMode: mode, autoStart: true,
    });
}

describe('the start write puts the anchor on the target, in the same write', () => {
    it.each<[TimerRecordMode, string[]]>([
        ['self', ['- [ ] 対象 @2026-09-21', '- [ ] 下', '']],
        ['child', ['- [ ] 対象 @2026-09-21', '- [ ] 下', '']],
        ['sibling', ['- [x] 対象 @2026-09-21', '- [ ] 下', '']],
    ])('%s: one write, and the target row carries the timer\'s anchor', async (mode, start) => {
        const contents = new Map([[FILE, start.join('\n')]]);
        const s = vaultSession(contents);
        const timer = await timerOn(s, mode);
        expect(timer.timerTargetId).toBeUndefined();

        const process = vi.spyOn(s.app.vault, 'process');
        expect(await s.recorder.writeStart(timer)).toBe(true);
        await s.settle(FILE);

        expect(process).toHaveBeenCalledTimes(1);
        const anchor = timer.timerTargetId!;
        expect(anchor).toMatch(/^tv-t-/);
        expect(timer.autoGeneratedTargetId).toBe(true);
        const targetLine = lines(contents).find(line => line.includes('対象') && line.endsWith(`^${anchor}`));
        expect(targetLine).toBeDefined();
        expect(s.index.getTaskByAnchor(FILE, anchor)?.content).toBe('対象');
        // The tail: the target itself for self, the line written for the others.
        if (mode === 'self') expect(timer.tailRecordBlockId).toBe(anchor);
        else expect(lines(contents).some(line => line.endsWith(`^${timer.tailRecordBlockId}`) && !line.includes('@2026-09-21 '))).toBe(true);
    });

    it('a target that has an anchor keeps it: no second ^id', async () => {
        const contents = new Map([[FILE, ['- [ ] 対象 @2026-09-21 ^mine', ''].join('\n')]]);
        const s = vaultSession(contents);
        const timer = await timerOn(s, 'child');
        expect(timer.timerTargetId).toBe('mine');

        expect(await s.recorder.writeStart(timer)).toBe(true);
        await s.settle(FILE);
        expect(timer.timerTargetId).toBe('mine');
        expect(lines(contents)[0]).toBe('- [ ] 対象 @2026-09-21 ^mine');
    });
});

describe('a target that cannot be anchored: the timer does not start', () => {
    it('a ^id another row carries too: not started, told so, nothing written', async () => {
        const contents = new Map([[FILE, ['- [ ] 対象 @2026-09-21 ^dup', '- [ ] 別 ^dup', ''].join('\n')]]);
        const before = contents.get(FILE);
        const s = vaultSession(contents);
        const timer = await timerOn(s, 'child');
        Notice.messages.length = 0;

        expect(await s.recorder.writeStart(timer)).toBe(false);
        expect(contents.get(FILE)).toBe(before);
        expect(Notice.messages).toHaveLength(1);
        expect(Notice.messages[0]).toContain('^dup');
    });

    it('a start write refused (the file changed since the reading): not started, nothing written', async () => {
        const contents = new Map([[FILE, ['- [ ] 対象 @2026-09-21', ''].join('\n')]]);
        const s = vaultSession(contents);
        const timer = await timerOn(s, 'self');
        const edited = ['- [ ] 上', '- [ ] 対象 @2026-09-21', ''].join('\n');
        contents.set(FILE, edited);

        expect(await s.recorder.writeStart(timer)).toBe(false);
        expect(contents.get(FILE)).toBe(edited);
    });
});

describe('the target is found by its anchor after a reload', () => {
    it('child: the running line gone, a line added above and a twin, reloaded: the record goes under the anchored target', async () => {
        const contents = new Map([[FILE, ['- [ ] 対象 @2026-09-21', '- [ ] 下', ''].join('\n')]]);
        const s = vaultSession(contents);
        const timer = await timerOn(s, 'child');
        expect(await s.recorder.writeStart(timer)).toBe(true);
        await s.settle(FILE);
        const anchor = timer.timerTargetId!;
        const saved = JSON.parse(JSON.stringify(timer)) as TimerInstance;
        s.dispose();

        // From outside: the running line deleted, a twin of the target and a line above.
        const kept = lines(contents).filter(line => !line.includes(`^${timer.tailRecordBlockId}`));
        contents.set(FILE, ['- [ ] 上', '- [ ] 対象 @2026-09-21', ...kept, ''].join('\n'));

        vi.useFakeTimers({ toFake: ['Date'] });
        vi.setSystemTime(Date.now() + 5_000);
        const next = vaultSession(contents);
        await next.scanAll();
        expect(await next.recorder.recordSessionEnd(saved)).toBe(true);
        await next.settle(FILE);

        const after = lines(contents);
        const at = after.findIndex(line => line.endsWith(`^${anchor}`));
        expect(at).toBe(2);
        expect(after[at + 1]).toMatch(/^\s+- \[x\] /);
        expect(after[1]).toBe('- [ ] 対象 @2026-09-21');
    });

    it('self: the next session leaves the target\'s anchor on it while the timer runs', async () => {
        const contents = new Map([[FILE, ['- [ ] 対象 @2026-09-21', ''].join('\n')]]);
        const s = vaultSession(contents);
        const timer = await timerOn(s, 'self');
        expect(await s.recorder.writeStart(timer)).toBe(true);
        await s.settle(FILE);
        const anchor = timer.timerTargetId!;
        timer.sessionCount = 1;
        timer.runState = 'suspended';

        expect(await s.recorder.startNextSession(timer)).toBe(true);
        await s.settle(FILE);
        expect(timer.timerTargetId).toBe(anchor);
        expect(lines(contents)[0]).toMatch(new RegExp(`\\^${anchor}$`));
        expect(timer.tailRecordBlockId).not.toBe(anchor);
    });
});
