import { describe, expect, it, vi } from 'vitest';
import type { App } from 'obsidian';
import { TimerRecorder } from '../../../src/timer/TimerRecorder';
import type { TimerInstance } from '../../../src/timer/TimerInstance';
import type { TimerStorageUtils } from '../../../src/timer/TimerStorageUtils';
import type TaskViewerPlugin from '../../../src/main';
import { makeTask } from '../helpers/makeTask';

/**
 * Releasing the tail's `^id` never touches the timer's target anchor
 * (`timerTargetId`): a tail equal to the target's anchor (self mode, first
 * session) is left alone entirely, and a tail of its own is released only
 * when `getTaskByAnchor` still finds the row that carries it.
 */

const FILE = 'notes/a.md';
const TARGET_ID = 'tv-inline:notes/a.md:ln:3';
const TAIL_ID = 'tv-inline:notes/a.md:ln:5';
const ANCHOR = 'tv-t-anchor';

function makeTimer(overrides: Partial<TimerInstance> = {}): TimerInstance {
    return {
        id: 'timer-1',
        taskId: TARGET_ID,
        taskName: 'target',
        taskOriginalText: '- [ ] target',
        taskFile: FILE,
        startTimeMs: 0,
        pausedElapsedTime: 0,
        phase: 'work',
        isRunning: true,
        runState: 'running',
        sessionCount: 0,
        recordedElapsedTime: 0,
        isExpanded: true,
        intervalId: null,
        recordMode: 'child',
        parserId: 'tv-inline',
        taskColor: '',
        timerType: 'countup',
        elapsedTime: 0,
        ...overrides,
    } as TimerInstance;
}

describe('TimerRecorder: taking the tail `^id` off', () => {
    const TAIL_BLOCK_ID = 'tv-t-tail';

    // `tailIsTarget`: the tail line carries the target's own anchor (self mode,
    // first session) — that anchor is never released while the timer runs.
    // `found`: whether `getTaskByAnchor` resolves the tail's own id to a row
    // (a row the user deleted resolves to nothing).
    function harness(opts: { tailIsTarget: boolean; found: boolean }) {
        const tailBlockId = opts.tailIsTarget ? ANCHOR : TAIL_BLOCK_ID;
        const tail = makeTask({ id: TAIL_ID, file: FILE, line: 5, content: 'record', blockId: tailBlockId, statusChar: 'x', endTime: '10:00' });
        const updateTask = vi.fn(async () => true);
        const waitForScan = vi.fn(async () => { /* the scan is done */ });
        const getTaskByAnchor = vi.fn((file: string, anchor: string) =>
            (opts.found && file === FILE && anchor === TAIL_BLOCK_ID) ? tail : undefined);
        const taskIndex = {
            getTasks: () => [tail],
            getTask: (id: string) => (id === TAIL_ID ? tail : undefined),
            getTaskByAnchor,
            updateTask,
            waitForScan,
            deleteTask: vi.fn(async () => true),
        };
        const plugin = { settings: {}, getTaskIndex: () => taskIndex } as unknown as TaskViewerPlugin;
        const recorder = new TimerRecorder({} as App, plugin, {} as TimerStorageUtils);
        recorder.resolveTailRecord = () => tail;
        const timer = makeTimer({
            tailRecordBlockId: tailBlockId,
            timerTargetId: ANCHOR,
            autoGeneratedTargetId: true,
        });
        return { recorder, timer, updateTask, getTaskByAnchor };
    }

    it.each([
        ['clearTailRecordId', (r: TimerRecorder, t: TimerInstance) => r.clearTailRecordId(t)],
        ['discardRunningPlaceholder', (r: TimerRecorder, t: TimerInstance) => r.discardRunningPlaceholder(t)],
    ] as const)('%s: a tail equal to the target\'s anchor is not released', async (_name, act) => {
        const h = harness({ tailIsTarget: true, found: true });

        await act(h.recorder, h.timer);

        expect(h.updateTask).not.toHaveBeenCalled();
        expect(h.timer.timerTargetId).toBe(ANCHOR);
        expect(h.timer.autoGeneratedTargetId).toBe(true);
    });

    it.each([
        ['clearTailRecordId', (r: TimerRecorder, t: TimerInstance) => r.clearTailRecordId(t)],
        ['discardRunningPlaceholder', (r: TimerRecorder, t: TimerInstance) => r.discardRunningPlaceholder(t)],
    ] as const)('%s: a tail found by its own anchor, different from the target\'s, is released — the target\'s anchor is untouched', async (_name, act) => {
        const h = harness({ tailIsTarget: false, found: true });

        await act(h.recorder, h.timer);

        expect(h.getTaskByAnchor).toHaveBeenCalledWith(FILE, TAIL_BLOCK_ID);
        expect(h.updateTask).toHaveBeenCalledWith(TAIL_ID, { blockId: undefined });
        expect(h.timer.timerTargetId).toBe(ANCHOR);
        expect(h.timer.autoGeneratedTargetId).toBe(true);
    });

    it.each([
        ['clearTailRecordId', (r: TimerRecorder, t: TimerInstance) => r.clearTailRecordId(t)],
        ['discardRunningPlaceholder', (r: TimerRecorder, t: TimerInstance) => r.discardRunningPlaceholder(t)],
    ] as const)('%s: a tail not found by its own anchor is not released', async (_name, act) => {
        const h = harness({ tailIsTarget: false, found: false });

        await act(h.recorder, h.timer);

        expect(h.updateTask).not.toHaveBeenCalled();
        expect(h.timer.timerTargetId).toBe(ANCHOR);
    });
});
