import { describe, it, expect } from 'vitest';
import { canTriggerFlow } from '../../../src/services/flow/FlowTrigger';
import { parseFlow } from '../../../src/services/flow/FlowParser';
import { DEFAULT_STATUS_DEFINITIONS, TaskFlow } from '../../../src/types';
import { makeTask } from '../helpers/makeTask';

// ---------------------------------------------------------------------------
// Issue 1: TimerMenuBuilder guard — completed command tasks must not show Track
// Self. The guard IS canTriggerFlow (single source of truth), so test it directly.
// ---------------------------------------------------------------------------

function repeatFlow(): TaskFlow {
    const raw = 'at(today + 1d)';
    return { raw, ...parseFlow(raw) };
}

describe('TimerMenuBuilder guard: completed command task suppression', () => {
    it('完了済みコマンドタスクに Track Self メニューを表示しない', () => {
        const task = makeTask({ statusChar: 'x', flow: repeatFlow() });
        expect(canTriggerFlow(task, DEFAULT_STATUS_DEFINITIONS)).toBe(true);
    });

    it('未完了コマンドタスクでは Track Self を許可する', () => {
        const task = makeTask({ statusChar: ' ', flow: repeatFlow() });
        expect(canTriggerFlow(task, DEFAULT_STATUS_DEFINITIONS)).toBe(false);
    });

    it('完了済みだがコマンドなしタスクでは Track Self を許可する', () => {
        const task = makeTask({ statusChar: 'x' });
        expect(canTriggerFlow(task, DEFAULT_STATUS_DEFINITIONS)).toBe(false);
    });

    it('未完了でコマンドなしタスクでは Track Self を許可する', () => {
        const task = makeTask({ statusChar: ' ' });
        expect(canTriggerFlow(task, DEFAULT_STATUS_DEFINITIONS)).toBe(false);
    });

    it('壊れたフロー（program=null）は発火しない', () => {
        const raw = 'evry mon';
        const task = makeTask({ statusChar: 'x', flow: { raw, ...parseFlow(raw) } });
        expect(canTriggerFlow(task, DEFAULT_STATUS_DEFINITIONS)).toBe(false);
    });

    it('Doing(/) は完了扱いでないため発火しない', () => {
        const task = makeTask({ statusChar: '/', flow: repeatFlow() });
        expect(canTriggerFlow(task, DEFAULT_STATUS_DEFINITIONS)).toBe(false);
    });

    it('Cancelled(-) は完了扱いのため発火する', () => {
        const task = makeTask({ statusChar: '-', flow: repeatFlow() });
        expect(canTriggerFlow(task, DEFAULT_STATUS_DEFINITIONS)).toBe(true);
    });
});

// ---------------------------------------------------------------------------
// Issue 2: blockId handling in updateTaskDirectly
// ---------------------------------------------------------------------------

/**
 * Extracted blockId resolution logic from TimerRecorder.updateTaskDirectly().
 * Determines the blockId value to write when completing a self-mode timer.
 */
function resolveBlockIdForUpdate(
    autoGeneratedTargetId: boolean | undefined,
    existingBlockId: string | undefined
): string | undefined {
    return autoGeneratedTargetId ? undefined : existingBlockId;
}

describe('updateTaskDirectly blockId handling', () => {
    it('autoGeneratedTargetId=true のとき blockId をクリアする', () => {
        const result = resolveBlockIdForUpdate(true, 'tv-timer-target-abc123');
        expect(result).toBeUndefined();
    });

    it('autoGeneratedTargetId=false のとき既存 blockId を保持する', () => {
        const result = resolveBlockIdForUpdate(false, 'my-reference');
        expect(result).toBe('my-reference');
    });

    it('autoGeneratedTargetId=undefined のとき既存 blockId を保持する', () => {
        const result = resolveBlockIdForUpdate(undefined, 'user-block');
        expect(result).toBe('user-block');
    });

    it('autoGeneratedTargetId=false で blockId が undefined のときも undefined を返す', () => {
        const result = resolveBlockIdForUpdate(false, undefined);
        expect(result).toBeUndefined();
    });
});
