/**
 * Floating Timer Widget
 * 
 * フローティングウィジェットとして複数のタイマー（Pomodoro/Countup）を管理。
 * アコーディオン形式で個別にトグル可能。
 */

import { App, setIcon, Notice, Menu, TFile, FileSystemAdapter } from 'obsidian';
import TaskViewerPlugin from '../main';
import { AudioUtils } from '../utils/AudioUtils';
import { InputModal } from '../modals/InputModal';
import { TimerInstance } from './TimerInstance';
import { TimerRecorder } from './TimerRecorder';
import { TimerProgressUI } from './TimerProgressUI';
import { Task } from '../types';
import {
    TIMER_TARGET_ID_PREFIX,
    isTimerTargetId
} from '../utils/TimerTargetIdUtils';
import { TaskIdGenerator } from '../utils/TaskIdGenerator';

interface PersistedTimer {
    id: string;
    taskId: string;
    taskName: string;
    taskOriginalText: string;
    taskFile: string;
    timerTargetId?: string;
    autoGeneratedTargetId?: boolean;
    startTimeMs: number;
    timeRemaining: number;
    totalTime: number;
    mode: 'work' | 'break' | 'idle';
    isRunning: boolean;
    isExpanded: boolean;
    customLabel: string;
    timerType: 'pomodoro' | 'countup';
    elapsedTime: number;
    pausedElapsedTime: number;
    autoRepeat: boolean;
    recordMode: 'child' | 'self';
    parserId: string;
}

interface PersistedTimerState {
    version: 3;
    ownerDeviceId: string;
    vaultFingerprint: string;
    updatedAtMs: number;
    timers: PersistedTimer[];
}

export class TimerWidget {
    private static readonly STORAGE_VERSION = 3;
    private static readonly STORAGE_KEY_PREFIX = 'task-viewer.active-timers';
    private static readonly LEGACY_STORAGE_KEY = 'task-viewer.active-timers.v2';
    private static readonly DEVICE_ID_KEY = 'task-viewer.device-id.v1';

    private app: App;
    private plugin: TaskViewerPlugin;
    private container: HTMLElement | null = null;
    private timers: Map<string, TimerInstance> = new Map();
    private isDragging = false;
    private dragOffset = { x: 0, y: 0 };
    private recorder: TimerRecorder;
    private readonly deviceId: string;
    private readonly vaultFingerprint: string;

    constructor(app: App, plugin: TaskViewerPlugin) {
        this.app = app;
        this.plugin = plugin;
        this.recorder = new TimerRecorder(app, plugin);
        this.deviceId = this.getOrCreateDeviceId();
        this.vaultFingerprint = this.resolveVaultFingerprint();
        this.cleanupLegacyStorage();
        this.restoreTimersFromStorage();
    }

    /**
     * Show the widget and start a new timer for the given task
     */
    show(
        taskId: string,
        taskName: string,
        taskOriginalText: string = '',
        taskFile: string = '',
        recordMode: 'child' | 'self' = 'child',
        parserId: string = 'at-notation',
        timerTargetId?: string
    ): void {
        // Create container if not exists
        if (!this.container) {
            this.createContainer();
        }

        // Check if timer already exists for this task
        if (this.hasActiveTimerForTask(taskId, timerTargetId)) {
            new Notice('This task already has an active timer');
            return;
        }

        // Create new timer instance (starts in idle mode - user must click Start)
        const timer: TimerInstance = {
            id: taskId,
            taskId: taskId,
            taskName: taskName,
            taskOriginalText: taskOriginalText,
            taskFile: taskFile,
            timerTargetId,
            autoGeneratedTargetId: this.isAutoManagedTimerTargetId(timerTargetId),
            startTime: new Date(),
            timeRemaining: this.plugin.settings.pomodoroWorkMinutes * 60,
            totalTime: this.plugin.settings.pomodoroWorkMinutes * 60,
            mode: 'idle',
            isRunning: false,
            isExpanded: true,
            intervalId: null,
            customLabel: '',
            timerType: 'pomodoro',
            elapsedTime: 0,
            startTimeMs: 0,
            pausedElapsedTime: 0,
            autoRepeat: false,
            recordMode: recordMode,
            parserId: parserId,
        };

        this.timers.set(taskId, timer);
        this.render();
        this.persistTimersToStorage();
        void this.ensureTimerTargetId(taskId);
    }

    /**
     * Show the widget and start a new countup timer for the given task
     * @param recordMode 'child' = add child task, 'self' = update this task's start/end
     * @param autoStart if true, start the timer immediately
     */
    showCountup(
        taskId: string,
        taskName: string,
        taskOriginalText: string = '',
        taskFile: string = '',
        recordMode: 'child' | 'self' = 'child',
        autoStart: boolean = false,
        parserId: string = 'at-notation',
        timerTargetId?: string
    ): void {
        // Create container if not exists
        if (!this.container) {
            this.createContainer();
        }

        // Check if timer already exists for this task
        if (this.hasActiveTimerForTask(taskId, timerTargetId)) {
            new Notice('This task already has an active timer');
            return;
        }

        // Create new countup timer instance
        const timer: TimerInstance = {
            id: taskId,
            taskId: taskId,
            taskName: taskName,
            taskOriginalText: taskOriginalText,
            taskFile: taskFile,
            timerTargetId,
            autoGeneratedTargetId: this.isAutoManagedTimerTargetId(timerTargetId),
            startTime: new Date(),
            timeRemaining: 0, // not used for countup
            totalTime: 0, // not used for countup
            mode: autoStart ? 'work' : 'idle',
            isRunning: autoStart,
            isExpanded: true,
            intervalId: null,
            customLabel: '',
            timerType: 'countup',
            elapsedTime: 0,
            startTimeMs: autoStart ? Date.now() : 0,
            pausedElapsedTime: 0,
            autoRepeat: false,
            recordMode: recordMode,
            parserId: parserId,
        };

        this.timers.set(taskId, timer);

        if (autoStart) {
            this.startTimer(taskId);
            AudioUtils.playStartSound();
        }

        this.render();
        this.persistTimersToStorage();
        void this.ensureTimerTargetId(taskId);
    }

    private createContainer(): void {
        this.container = document.body.createDiv('timer-widget');
        this.container.style.position = 'fixed';
        this.container.style.right = '20px';
        this.container.style.bottom = '20px';

        // Make draggable
        this.setupDrag();
    }

    private setupDrag(): void {
        if (!this.container) return;

        const header = this.container;

        header.addEventListener('pointerdown', (e) => {
            if ((e.target as HTMLElement).closest('.timer-widget__item')) {
                // Don't start drag if clicking inside an item
                if ((e.target as HTMLElement).closest('button, input')) return;
            }

            this.isDragging = true;
            const rect = this.container!.getBoundingClientRect();
            this.dragOffset.x = e.clientX - rect.left;
            this.dragOffset.y = e.clientY - rect.top;
            this.container!.style.cursor = 'grabbing';

            // Capture pointer for reliable tracking across boundaries
            header.setPointerCapture(e.pointerId);
        });

        header.addEventListener('pointermove', (e) => {
            if (!this.isDragging || !this.container) return;

            const x = e.clientX - this.dragOffset.x;
            const y = e.clientY - this.dragOffset.y;

            this.container.style.left = `${x}px`;
            this.container.style.top = `${y}px`;
            this.container.style.right = 'auto';
            this.container.style.bottom = 'auto';
        });

        header.addEventListener('pointerup', (e) => {
            this.isDragging = false;
            if (this.container) {
                this.container.style.cursor = 'grab';
            }
            header.releasePointerCapture(e.pointerId);
        });

        header.addEventListener('pointercancel', (e) => {
            this.isDragging = false;
            if (this.container) {
                this.container.style.cursor = 'grab';
            }
            header.releasePointerCapture(e.pointerId);
        });
    }

    private startTimer(taskId: string): void {
        const timer = this.timers.get(taskId);
        if (!timer) return;

        timer.intervalId = window.setInterval(() => {
            this.tick(taskId);
        }, 1000);
    }

    private stopTimer(taskId: string): void {
        const timer = this.timers.get(taskId);
        if (!timer || timer.intervalId === null) return;

        window.clearInterval(timer.intervalId);
        timer.intervalId = null;
    }

    private tick(taskId: string): void {
        const timer = this.timers.get(taskId);
        if (!timer || !timer.isRunning) return;

        // Calculate elapsed time based on real time (not tick count)
        const now = Date.now();
        const currentSessionElapsed = Math.floor((now - timer.startTimeMs) / 1000);
        const totalElapsed = timer.pausedElapsedTime + currentSessionElapsed;

        if (timer.timerType === 'countup') {
            // Countup mode: update elapsed time based on real time
            timer.elapsedTime = totalElapsed;
            this.renderTimerItem(taskId);
        } else {
            // Pomodoro mode: calculate remaining time based on real time
            timer.timeRemaining = Math.max(0, timer.totalTime - totalElapsed);
            if (timer.timeRemaining > 0) {
                this.renderTimerItem(taskId);
            } else {
                this.handleComplete(taskId);
            }
        }
    }

    private async handleComplete(taskId: string): Promise<void> {
        const timer = this.timers.get(taskId);
        if (!timer) return;

        this.stopTimer(taskId);

        if (timer.mode === 'work') {
            // Work complete - add child task record
            AudioUtils.playWorkCompleteChime();
            new Notice(`🍅 ${timer.taskName} - Pomodoro complete!`);

            await this.recorder.addPomodoroRecord(timer);

            // Start break
            timer.mode = 'break';
            timer.timeRemaining = this.plugin.settings.pomodoroBreakMinutes * 60;
            timer.totalTime = this.plugin.settings.pomodoroBreakMinutes * 60;
            timer.startTimeMs = Date.now();
            timer.pausedElapsedTime = 0;
            timer.isRunning = true;
            this.startTimer(taskId);
        } else {
            // Break complete
            AudioUtils.playBreakCompleteChime();
            new Notice(`☕ ${timer.taskName} - Break complete!`);

            if (timer.autoRepeat) {
                // Auto-repeat: start work session again
                timer.mode = 'work';
                timer.timeRemaining = this.plugin.settings.pomodoroWorkMinutes * 60;
                timer.totalTime = this.plugin.settings.pomodoroWorkMinutes * 60;
                timer.startTime = new Date();
                timer.startTimeMs = Date.now();
                timer.pausedElapsedTime = 0;
                timer.isRunning = true;
                this.startTimer(taskId);
                AudioUtils.playStartSound();
            } else {
                // Reset to idle
                timer.mode = 'idle';
                timer.timeRemaining = this.plugin.settings.pomodoroWorkMinutes * 60;
                timer.totalTime = this.plugin.settings.pomodoroWorkMinutes * 60;
                timer.startTimeMs = 0;
                timer.pausedElapsedTime = 0;
                timer.isRunning = false;
            }
        }

        this.render();
        this.persistTimersToStorage();
    }

    private render(): void {
        if (!this.container) return;
        this.container.empty();

        if (this.timers.size === 0) {
            this.container.remove();
            this.container = null;
            return;
        }

        for (const [taskId] of this.timers) {
            this.renderTimerItem(taskId);
        }
    }

    private renderTimerItem(taskId: string): void {
        if (!this.container) return;

        const timer = this.timers.get(taskId);
        if (!timer) return;

        // Find or create item container
        let itemEl = this.container.querySelector(`[data-task-id="${taskId}"]`) as HTMLElement;
        const isNewItem = !itemEl;

        if (isNewItem) {
            itemEl = this.container.createDiv('timer-widget__item');
            itemEl.dataset.taskId = taskId;
        }

        // Only rebuild if new item or structure changed (e.g., expanded/collapsed toggle)
        const currentExpanded = itemEl.dataset.expanded === 'true';
        const needsRebuild = isNewItem || currentExpanded !== timer.isExpanded;

        if (needsRebuild) {
            itemEl.empty();
            itemEl.dataset.expanded = timer.isExpanded.toString();

            // Header
            const header = itemEl.createDiv('timer-widget__header');

            const titleSpan = header.createSpan('timer-widget__title');
            titleSpan.setText(timer.taskName);

            if (!timer.isExpanded) {
                // Show time in header when collapsed
                const timeSpan = header.createSpan('timer-widget__header-time');
                timeSpan.dataset.timeDisplay = 'header';
                if (timer.timerType === 'countup') {
                    timeSpan.setText(this.formatTime(timer.elapsedTime));
                } else {
                    timeSpan.setText(this.formatTime(timer.timeRemaining));
                    if (timer.mode === 'break') {
                        timeSpan.addClass('timer-widget__header-time--break');
                    }
                }
            }

            // Settings button (only for pomodoro)
            if (timer.timerType !== 'countup') {
                const settingsBtn = header.createEl('button', { cls: 'timer-widget__settings-btn' });
                setIcon(settingsBtn, 'settings');
                settingsBtn.onclick = (e) => {
                    e.stopPropagation();
                    this.showSettingsMenu(e, taskId);
                };
            }

            // Toggle button
            const toggleBtn = header.createEl('button', { cls: 'timer-widget__toggle-btn' });
            setIcon(toggleBtn, timer.isExpanded ? 'chevron-down' : 'chevron-right');
            toggleBtn.onclick = () => {
                timer.isExpanded = !timer.isExpanded;
                this.renderTimerItem(taskId);
                this.persistTimersToStorage();
            };

            // Close button
            const closeBtn = header.createEl('button', { cls: 'timer-widget__close-btn' });
            setIcon(closeBtn, 'x');
            closeBtn.onclick = () => {
                this.closeTimer(taskId);
            };

            // Expandable content
            if (timer.isExpanded) {
                const content = itemEl.createDiv('timer-widget__content');
                this.renderTimerUI(content, timer);
            }
        } else {
            // Partial update: only update time displays and progress ring
            this.updateTimerDisplay(itemEl, timer);
        }
    }

    private updateTimerDisplay(itemEl: HTMLElement, timer: TimerInstance): void {
        // Update header time (when collapsed)
        const headerTime = itemEl.querySelector('[data-time-display="header"]') as HTMLElement;
        if (headerTime) {
            if (timer.timerType === 'countup') {
                headerTime.setText(this.formatTime(timer.elapsedTime));
            } else {
                headerTime.setText(this.formatTime(timer.timeRemaining));
            }
        }

        // Update progress ring and time display using TimerProgressUI
        TimerProgressUI.updateDisplay(itemEl, timer, this.formatTime.bind(this));
    }

    private renderTimerUI(container: HTMLElement, timer: TimerInstance): void {
        // Custom label input field - only show for 'child' recordMode (not for 'self')
        if (timer.recordMode !== 'self') {
            const labelContainer = container.createDiv('timer-widget__label-container');
            const labelInput = labelContainer.createEl('input', {
                type: 'text',
                cls: 'timer-widget__label-input',
                placeholder: 'What are you working on? (empty = 🍅)',
                value: timer.customLabel
            });
            labelInput.oninput = () => {
                timer.customLabel = labelInput.value;
                this.persistTimersToStorage();
            };
        }

        // Circular progress
        const progressContainer = container.createDiv('timer-widget__progress-container');
        this.renderCircularProgress(progressContainer, timer);

        // Controls
        const controls = container.createDiv('timer-widget__controls');
        this.renderControls(controls, timer);
    }

    private renderCircularProgress(container: HTMLElement, timer: TimerInstance): void {
        TimerProgressUI.render(container, timer, this.formatTime.bind(this));
    }

    private renderControls(container: HTMLElement, timer: TimerInstance): void {
        if (timer.timerType === 'countup') {
            // Countup mode controls
            this.renderCountupControls(container, timer);
        } else {
            // Pomodoro mode controls
            this.renderPomodoroControls(container, timer);
        }
    }

    private renderPomodoroControls(container: HTMLElement, timer: TimerInstance): void {
        if (timer.mode === 'idle') {
            const startBtn = container.createEl('button', {
                cls: 'timer-widget__btn timer-widget__btn--primary'
            });
            setIcon(startBtn, 'play');
            startBtn.createSpan({ text: ' Start' });
            startBtn.onclick = () => {
                timer.mode = 'work';
                timer.startTime = new Date();
                timer.startTimeMs = Date.now();
                timer.pausedElapsedTime = 0;
                timer.isRunning = true;
                this.startTimer(timer.id);
                AudioUtils.playStartSound();
                this.render();
                this.persistTimersToStorage();
            };
        } else if (timer.isRunning) {
            const pauseBtn = container.createEl('button', {
                cls: 'timer-widget__btn timer-widget__btn--secondary'
            });
            setIcon(pauseBtn, 'pause');
            pauseBtn.createSpan({ text: ' Pause' });
            pauseBtn.onclick = () => {
                // Save accumulated elapsed time before pause
                const now = Date.now();
                const currentSessionElapsed = Math.floor((now - timer.startTimeMs) / 1000);
                timer.pausedElapsedTime += currentSessionElapsed;
                timer.isRunning = false;
                this.stopTimer(timer.id);
                this.render();
                this.persistTimersToStorage();
            };

            const resetBtn = container.createEl('button', {
                cls: 'timer-widget__btn timer-widget__btn--danger'
            });
            setIcon(resetBtn, 'x');
            resetBtn.createSpan({ text: ' Reset' });
            resetBtn.onclick = () => {
                this.resetTimer(timer.id);
            };
        } else {
            const resumeBtn = container.createEl('button', {
                cls: 'timer-widget__btn timer-widget__btn--primary'
            });
            setIcon(resumeBtn, 'play');
            resumeBtn.createSpan({ text: ' Resume' });
            resumeBtn.onclick = () => {
                timer.startTimeMs = Date.now(); // Reset start time for new session
                timer.isRunning = true;
                this.startTimer(timer.id);
                AudioUtils.playStartSound();
                this.render();
                this.persistTimersToStorage();
            };

            const resetBtn = container.createEl('button', {
                cls: 'timer-widget__btn timer-widget__btn--danger'
            });
            setIcon(resetBtn, 'x');
            resetBtn.createSpan({ text: ' Reset' });
            resetBtn.onclick = () => {
                this.resetTimer(timer.id);
            };
        }
    }

    private renderCountupControls(container: HTMLElement, timer: TimerInstance): void {
        if (timer.mode === 'idle') {
            // Start button
            const startBtn = container.createEl('button', {
                cls: 'timer-widget__btn timer-widget__btn--primary'
            });
            setIcon(startBtn, 'play');
            startBtn.createSpan({ text: ' Start' });
            startBtn.onclick = () => {
                timer.mode = 'work';
                timer.startTime = new Date();
                timer.startTimeMs = Date.now();
                timer.pausedElapsedTime = 0;
                timer.elapsedTime = 0;
                timer.isRunning = true;
                this.startTimer(timer.id);
                AudioUtils.playStartSound();
                this.render();
                this.persistTimersToStorage();
            };
        } else if (timer.isRunning) {
            // Stop button (saves record)
            const stopBtn = container.createEl('button', {
                cls: 'timer-widget__btn timer-widget__btn--secondary'
            });
            setIcon(stopBtn, 'square');
            stopBtn.createSpan({ text: ' Stop' });
            stopBtn.onclick = async () => {
                timer.isRunning = false;
                this.stopTimer(timer.id);
                AudioUtils.playWorkCompleteChime();

                // Record based on recordMode
                if (timer.recordMode === 'self') {
                    await this.recorder.updateTaskDirectly(timer);
                } else {
                    await this.recorder.addCountupRecord(timer);
                }

                this.closeTimer(timer.id);
            };

            // Cancel button (no record)
            const cancelBtn = container.createEl('button', {
                cls: 'timer-widget__btn timer-widget__btn--danger'
            });
            setIcon(cancelBtn, 'x');
            cancelBtn.createSpan({ text: ' Cancel' });
            cancelBtn.onclick = () => {
                this.closeTimer(timer.id);
            };
        } else {
            // Paused state (shouldn't normally happen for countup, but handle it)
            const resumeBtn = container.createEl('button', {
                cls: 'timer-widget__btn timer-widget__btn--primary'
            });
            setIcon(resumeBtn, 'play');
            resumeBtn.createSpan({ text: ' Resume' });
            resumeBtn.onclick = () => {
                timer.startTimeMs = Date.now(); // Reset start time for new session
                timer.isRunning = true;
                this.startTimer(timer.id);
                this.render();
                this.persistTimersToStorage();
            };

            const cancelBtn = container.createEl('button', {
                cls: 'timer-widget__btn timer-widget__btn--danger'
            });
            setIcon(cancelBtn, 'x');
            cancelBtn.createSpan({ text: ' Cancel' });
            cancelBtn.onclick = () => {
                this.closeTimer(timer.id);
            };
        }
    }

    private resetTimer(taskId: string): void {
        const timer = this.timers.get(taskId);
        if (!timer) return;

        this.stopTimer(taskId);
        timer.mode = 'idle';
        timer.timeRemaining = this.plugin.settings.pomodoroWorkMinutes * 60;
        timer.totalTime = this.plugin.settings.pomodoroWorkMinutes * 60;
        timer.startTimeMs = 0;
        timer.pausedElapsedTime = 0;
        timer.isRunning = false;
        this.render();
        this.persistTimersToStorage();
    }

    private closeTimer(taskId: string): void {
        const timer = this.timers.get(taskId);
        if (!timer) return;

        this.stopTimer(taskId);
        this.timers.delete(taskId);
        this.render();
        this.persistTimersToStorage();
        void this.cleanupGeneratedTargetId(timer);
    }

    private formatTime(seconds: number): string {
        const mins = Math.floor(seconds / 60);
        const secs = seconds % 60;
        return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
    }

    handleFileRename(oldPath: string, newPath: string): void {
        let changed = false;

        for (const timer of this.timers.values()) {
            if (timer.taskFile === oldPath) {
                timer.taskFile = newPath;
                changed = true;
            }

            const renamedTaskId = TaskIdGenerator.renameFile(timer.taskId, oldPath, newPath);
            if (renamedTaskId !== timer.taskId) {
                timer.taskId = renamedTaskId;
                changed = true;
            }
        }

        if (changed) {
            this.persistTimersToStorage();
        }
    }

    private hasActiveTimerForTask(taskId: string, timerTargetId?: string): boolean {
        if (this.timers.has(taskId)) {
            return true;
        }

        if (!timerTargetId) {
            return false;
        }

        for (const timer of this.timers.values()) {
            if (timer.timerTargetId === timerTargetId) {
                return true;
            }
        }

        return false;
    }

    private async ensureTimerTargetId(taskId: string): Promise<void> {
        const timer = this.timers.get(taskId);
        if (!timer) return;
        if (timer.taskId.startsWith('daily-')) return;

        if (timer.timerTargetId) {
            timer.autoGeneratedTargetId = this.isAutoManagedTimerTargetId(timer.timerTargetId);
            this.persistTimersToStorage();
            return;
        }

        if (timer.parserId === 'at-notation') {
            await this.ensureInlineTimerTargetId(timer);
            return;
        }

        if (timer.parserId === 'frontmatter') {
            await this.ensureFrontmatterTimerTargetId(timer);
        }
    }

    private async ensureInlineTimerTargetId(timer: TimerInstance): Promise<void> {
        const taskIndex = this.plugin.getTaskIndex();
        const currentTask = this.resolveInlineTaskForTimer(timer);
        if (!currentTask) return;

        if (currentTask.timerTargetId) {
            timer.taskId = currentTask.id;
            timer.taskFile = currentTask.file;
            timer.taskOriginalText = currentTask.originalText;
            timer.timerTargetId = currentTask.timerTargetId;
            timer.autoGeneratedTargetId = this.isAutoManagedTimerTargetId(currentTask.timerTargetId);
            this.persistTimersToStorage();
            return;
        }

        // Preserve user-defined non-timer block IDs and use them as stable lookup keys.
        if (currentTask.blockId) {
            timer.taskId = currentTask.id;
            timer.taskFile = currentTask.file;
            timer.taskOriginalText = currentTask.originalText;
            timer.timerTargetId = currentTask.blockId;
            timer.autoGeneratedTargetId = false;
            this.persistTimersToStorage();
            return;
        }

        const newTargetId = this.generateTimerTargetId();
        try {
            await taskIndex.updateTask(currentTask.id, { blockId: newTargetId });
            await taskIndex.waitForScan(currentTask.file);

            const updatedTask =
                this.findInlineTaskByTimerTargetId(currentTask.file, newTargetId)
                || this.resolveInlineTaskForTimer(timer);
            if (updatedTask) {
                timer.taskId = updatedTask.id;
                timer.taskFile = updatedTask.file;
                timer.taskOriginalText = updatedTask.originalText;
                timer.timerTargetId = newTargetId;
                timer.autoGeneratedTargetId = true;
                this.persistTimersToStorage();
            }
        } catch (error) {
            console.error('[TimerWidget] Failed to assign timer target ID for inline task:', error);
        }
    }

    private async ensureFrontmatterTimerTargetId(timer: TimerInstance): Promise<void> {
        const taskIndex = this.plugin.getTaskIndex();
        const currentTask = this.resolveFrontmatterTaskForTimer(timer);
        if (!currentTask) return;

        if (currentTask.timerTargetId) {
            timer.taskId = currentTask.id;
            timer.taskFile = currentTask.file;
            timer.timerTargetId = currentTask.timerTargetId;
            timer.autoGeneratedTargetId = this.isAutoManagedTimerTargetId(currentTask.timerTargetId);
            this.persistTimersToStorage();
            return;
        }

        const file = this.app.vault.getAbstractFileByPath(currentTask.file);
        if (!(file instanceof TFile)) return;

        const newTargetId = this.generateTimerTargetId();
        try {
            const timerTargetIdKey = this.plugin.settings.frontmatterTaskKeys.timerTargetId;
            // @ts-ignore - processFrontMatter is available in Obsidian API
            await this.app.fileManager.processFrontMatter(file, (frontmatter: any) => {
                frontmatter[timerTargetIdKey] = newTargetId;
            });
            await taskIndex.waitForScan(currentTask.file);

            const updatedTask =
                this.findFrontmatterTaskByTimerTargetId(newTargetId, currentTask.file)
                || this.resolveFrontmatterTaskForTimer(timer);
            if (updatedTask) {
                timer.taskId = updatedTask.id;
                timer.taskFile = updatedTask.file;
                timer.timerTargetId = newTargetId;
                timer.autoGeneratedTargetId = true;
                this.persistTimersToStorage();
            }
        } catch (error) {
            console.error('[TimerWidget] Failed to assign timer target ID for frontmatter task:', error);
        }
    }

    private resolveInlineTaskForTimer(timer: TimerInstance): Task | undefined {
        if (timer.parserId !== 'at-notation') {
            return undefined;
        }

        const taskIndex = this.plugin.getTaskIndex();

        if (timer.timerTargetId) {
            const byTargetInFile = timer.taskFile
                ? this.findInlineTaskByTimerTargetId(timer.taskFile, timer.timerTargetId)
                : undefined;
            if (byTargetInFile) return byTargetInFile;

            const byTargetId = taskIndex
                .getTasks()
                .find((task) =>
                    task.parserId === 'at-notation'
                    && (task.timerTargetId === timer.timerTargetId || task.blockId === timer.timerTargetId)
                );
            if (byTargetId) return byTargetId;
        }

        const byId = taskIndex.getTask(timer.taskId);
        if (byId && byId.parserId === 'at-notation' && (!timer.taskFile || byId.file === timer.taskFile)) {
            return byId;
        }

        if (timer.taskOriginalText && timer.taskFile) {
            return taskIndex
                .getTasks()
                .find((task) =>
                    task.parserId === 'at-notation'
                    && task.file === timer.taskFile
                    && task.originalText === timer.taskOriginalText
                );
        }

        return undefined;
    }

    private resolveFrontmatterTaskForTimer(timer: TimerInstance): Task | undefined {
        if (timer.parserId !== 'frontmatter') {
            return undefined;
        }

        if (timer.timerTargetId) {
            const byTargetInFile = this.findFrontmatterTaskByTimerTargetId(timer.timerTargetId, timer.taskFile);
            if (byTargetInFile) return byTargetInFile;

            const byTargetId = this.findFrontmatterTaskByTimerTargetId(timer.timerTargetId);
            if (byTargetId) return byTargetId;
        }

        const taskIndex = this.plugin.getTaskIndex();
        const byId = taskIndex.getTask(timer.taskId);
        if (byId && byId.parserId === 'frontmatter') {
            return byId;
        }

        if (!timer.taskFile) return undefined;
        return taskIndex
            .getTasks()
            .find((task) => task.parserId === 'frontmatter' && task.file === timer.taskFile);
    }

    private findInlineTaskByTimerTargetId(filePath: string, timerTargetId: string): Task | undefined {
        return this.plugin
            .getTaskIndex()
            .getTasks()
            .find((task) =>
                task.parserId === 'at-notation'
                && task.file === filePath
                && (task.timerTargetId === timerTargetId || task.blockId === timerTargetId)
            );
    }

    private findFrontmatterTaskByTimerTargetId(timerTargetId: string, filePath?: string): Task | undefined {
        return this.plugin
            .getTaskIndex()
            .getTasks()
            .find((task) =>
                task.parserId === 'frontmatter'
                && task.timerTargetId === timerTargetId
                && (!filePath || task.file === filePath)
            );
    }

    private getOrCreateDeviceId(): string {
        try {
            const existing = window.localStorage.getItem(TimerWidget.DEVICE_ID_KEY);
            if (existing && existing.trim()) {
                return existing;
            }
            const newId = this.generateStableId('dev');
            window.localStorage.setItem(TimerWidget.DEVICE_ID_KEY, newId);
            return newId;
        } catch {
            return 'dev-unknown';
        }
    }

    private resolveVaultFingerprint(): string {
        const adapter = this.app.vault.adapter;
        const basePath = adapter instanceof FileSystemAdapter ? adapter.getBasePath() : '';
        const fallbackName = this.app.vault.getName();
        const rawIdentity = basePath && basePath.trim() ? basePath : fallbackName;
        const normalizedIdentity = (rawIdentity || 'unknown-vault').trim().toLowerCase();
        return this.hashToHex(normalizedIdentity);
    }

    private hashToHex(raw: string): string {
        let hash = 5381;
        for (let i = 0; i < raw.length; i++) {
            hash = ((hash << 5) + hash) + raw.charCodeAt(i);
        }
        return (hash >>> 0).toString(16).padStart(8, '0');
    }

    private getStorageKey(): string {
        return `${TimerWidget.STORAGE_KEY_PREFIX}.v${TimerWidget.STORAGE_VERSION}:${this.vaultFingerprint}`;
    }

    private cleanupLegacyStorage(): void {
        try {
            window.localStorage.removeItem(TimerWidget.LEGACY_STORAGE_KEY);
        } catch {
            // noop
        }
    }

    private generateStableId(prefix: string): string {
        if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
            return `${prefix}-${crypto.randomUUID()}`;
        }
        return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
    }

    private generateTimerTargetId(): string {
        const raw = this.generateStableId('target').replace(/^target-/, '');
        return `${TIMER_TARGET_ID_PREFIX}${raw}`.replace(/[^A-Za-z0-9-]/g, '');
    }

    private isAutoManagedTimerTargetId(timerTargetId?: string): boolean {
        return isTimerTargetId(timerTargetId);
    }

    private async cleanupGeneratedTargetId(timer: TimerInstance): Promise<void> {
        if (!timer.autoGeneratedTargetId) return;
        if (!timer.timerTargetId) return;
        if (!this.isAutoManagedTimerTargetId(timer.timerTargetId)) return;
        if (this.hasAnotherActiveTimerWithTarget(timer.timerTargetId)) return;

        if (timer.parserId === 'at-notation') {
            await this.removeInlineTimerTargetId(timer);
            return;
        }

        if (timer.parserId === 'frontmatter') {
            await this.removeFrontmatterTimerTargetId(timer);
        }
    }

    private hasAnotherActiveTimerWithTarget(timerTargetId: string): boolean {
        for (const timer of this.timers.values()) {
            if (timer.timerTargetId === timerTargetId) {
                return true;
            }
        }
        return false;
    }

    private async removeInlineTimerTargetId(timer: TimerInstance): Promise<void> {
        const taskIndex = this.plugin.getTaskIndex();
        let targetTask: Task | undefined;

        if (timer.taskFile) {
            targetTask = this.findInlineTaskByTimerTargetId(timer.taskFile, timer.timerTargetId!);
        }
        if (!targetTask) {
            targetTask = taskIndex
                .getTasks()
                .find((task) => task.parserId === 'at-notation' && task.timerTargetId === timer.timerTargetId);
        }
        if (!targetTask) return;

        if (targetTask.blockId !== timer.timerTargetId) {
            return;
        }

        try {
            await taskIndex.updateTask(targetTask.id, { blockId: undefined });
            await taskIndex.waitForScan(targetTask.file);
        } catch (error) {
            console.error('[TimerWidget] Failed to remove inline timer target ID:', error);
        }
    }

    private async removeFrontmatterTimerTargetId(timer: TimerInstance): Promise<void> {
        let targetPath = timer.taskFile;
        const targetTask = this.findFrontmatterTaskByTimerTargetId(timer.timerTargetId!);
        if (targetTask) {
            targetPath = targetTask.file;
        }
        if (!targetPath) return;

        const file = this.app.vault.getAbstractFileByPath(targetPath);
        if (!(file instanceof TFile)) return;

        try {
            const timerTargetIdKey = this.plugin.settings.frontmatterTaskKeys.timerTargetId;
            // @ts-ignore - processFrontMatter is available in Obsidian API
            await this.app.fileManager.processFrontMatter(file, (frontmatter: any) => {
                if (frontmatter?.[timerTargetIdKey] === timer.timerTargetId) {
                    delete frontmatter[timerTargetIdKey];
                }
            });
            await this.plugin.getTaskIndex().waitForScan(targetPath);
        } catch (error) {
            console.error('[TimerWidget] Failed to remove frontmatter timer target ID:', error);
        }
    }

    private persistTimersToStorage(): void {
        const storageKey = this.getStorageKey();
        try {
            if (this.timers.size === 0) {
                window.localStorage.removeItem(storageKey);
                return;
            }

            const payload: PersistedTimerState = {
                version: TimerWidget.STORAGE_VERSION,
                ownerDeviceId: this.deviceId,
                vaultFingerprint: this.vaultFingerprint,
                updatedAtMs: Date.now(),
                timers: Array.from(this.timers.values()).map((timer) => this.toPersistedTimer(timer))
            };

            window.localStorage.setItem(storageKey, JSON.stringify(payload));
        } catch (error) {
            console.error('[TimerWidget] Failed to persist timers:', error);
        }
    }

    private restoreTimersFromStorage(): void {
        const storageKey = this.getStorageKey();
        try {
            const raw = window.localStorage.getItem(storageKey);
            if (!raw) return;

            const parsed = JSON.parse(raw) as PersistedTimerState;
            if (
                !parsed
                || parsed.version !== TimerWidget.STORAGE_VERSION
                || parsed.vaultFingerprint !== this.vaultFingerprint
                || !Array.isArray(parsed.timers)
            ) {
                window.localStorage.removeItem(storageKey);
                return;
            }
            if (parsed.ownerDeviceId !== this.deviceId) {
                return;
            }

            for (const persisted of parsed.timers) {
                const timer = this.fromPersistedTimer(persisted);
                if (!timer) continue;

                this.reconcileRestoredTimer(timer);
                this.timers.set(timer.id, timer);
            }

            if (this.timers.size === 0) {
                this.persistTimersToStorage();
                return;
            }

            if (!this.container) {
                this.createContainer();
            }

            for (const [timerId, timer] of this.timers) {
                if (timer.isRunning) {
                    if (timer.timerType === 'pomodoro' && timer.timeRemaining <= 0) {
                        void this.handleComplete(timerId);
                    } else {
                        this.startTimer(timerId);
                    }
                }

                if (!timer.timerTargetId && !timer.taskId.startsWith('daily-')) {
                    void this.ensureTimerTargetId(timerId);
                }
            }

            this.render();
        } catch (error) {
            window.localStorage.removeItem(storageKey);
            console.error('[TimerWidget] Failed to restore timers:', error);
        }
    }

    private toPersistedTimer(timer: TimerInstance): PersistedTimer {
        return {
            id: timer.id,
            taskId: timer.taskId,
            taskName: timer.taskName,
            taskOriginalText: timer.taskOriginalText,
            taskFile: timer.taskFile,
            timerTargetId: timer.timerTargetId,
            autoGeneratedTargetId: timer.autoGeneratedTargetId,
            startTimeMs: timer.startTimeMs,
            timeRemaining: timer.timeRemaining,
            totalTime: timer.totalTime,
            mode: timer.mode,
            isRunning: timer.isRunning,
            isExpanded: timer.isExpanded,
            customLabel: timer.customLabel,
            timerType: timer.timerType,
            elapsedTime: timer.elapsedTime,
            pausedElapsedTime: timer.pausedElapsedTime,
            autoRepeat: timer.autoRepeat,
            recordMode: timer.recordMode,
            parserId: timer.parserId
        };
    }

    private fromPersistedTimer(persisted: PersistedTimer): TimerInstance | null {
        if (!persisted || !persisted.id || !persisted.taskId) {
            return null;
        }

        const taskId = persisted.taskId;
        if (!taskId.startsWith('daily-') && !TaskIdGenerator.parse(taskId)) {
            return null;
        }

        return {
            id: persisted.id,
            taskId,
            taskName: persisted.taskName || 'Untitled',
            taskOriginalText: persisted.taskOriginalText || '',
            taskFile: persisted.taskFile || '',
            timerTargetId: persisted.timerTargetId,
            autoGeneratedTargetId: persisted.autoGeneratedTargetId ?? this.isAutoManagedTimerTargetId(persisted.timerTargetId),
            startTime: new Date(persisted.startTimeMs || Date.now()),
            timeRemaining: persisted.timeRemaining || 0,
            totalTime: persisted.totalTime || 0,
            mode: persisted.mode || 'idle',
            isRunning: !!persisted.isRunning,
            isExpanded: persisted.isExpanded !== false,
            intervalId: null,
            customLabel: persisted.customLabel || '',
            timerType: persisted.timerType || 'countup',
            elapsedTime: persisted.elapsedTime || 0,
            startTimeMs: persisted.startTimeMs || 0,
            pausedElapsedTime: persisted.pausedElapsedTime || 0,
            autoRepeat: !!persisted.autoRepeat,
            recordMode: persisted.recordMode || 'child',
            parserId: persisted.parserId || 'at-notation'
        };
    }

    private reconcileRestoredTimer(timer: TimerInstance): void {
        if (timer.timerType === 'countup' && !timer.isRunning) {
            timer.elapsedTime = Math.max(timer.elapsedTime, timer.pausedElapsedTime);
            return;
        }

        if (!timer.isRunning || timer.startTimeMs <= 0) {
            return;
        }

        const now = Date.now();
        const currentSessionElapsed = Math.floor((now - timer.startTimeMs) / 1000);
        const totalElapsed = Math.max(0, timer.pausedElapsedTime + currentSessionElapsed);

        if (timer.timerType === 'countup') {
            timer.elapsedTime = totalElapsed;
            return;
        }

        timer.timeRemaining = Math.max(0, timer.totalTime - totalElapsed);
    }

    private showSettingsMenu(e: MouseEvent, taskId: string): void {
        const timer = this.timers.get(taskId);
        if (!timer) return;

        const menu = new Menu();

        menu.addItem((item) => {
            item.setTitle('Work Duration').setDisabled(true);
        });

        const workOptions = [15, 25, 30, 45, 50];
        workOptions.forEach((mins) => {
            menu.addItem((item) => {
                const current = this.plugin.settings.pomodoroWorkMinutes;
                item.setTitle(`  ${mins} min${current === mins ? ' ✓' : ''}`)
                    .onClick(async () => {
                        this.plugin.settings.pomodoroWorkMinutes = mins;
                        await this.plugin.saveSettings();
                        // Update timer if in idle
                        if (timer.mode === 'idle') {
                            timer.timeRemaining = mins * 60;
                            timer.totalTime = mins * 60;
                            this.render();
                        }
                        this.persistTimersToStorage();
                    });
            });
        });

        menu.addItem((item) => {
            const current = this.plugin.settings.pomodoroWorkMinutes;
            const isCustom = !workOptions.includes(current);
            item.setTitle(`  Custom...${isCustom ? ` (${current}min) ✓` : ''}`)
                .onClick(() => {
                    new InputModal(
                        this.app,
                        'Work Duration',
                        'Minutes (1-120)',
                        current.toString(),
                        async (value) => {
                            const mins = parseInt(value);
                            if (!isNaN(mins) && mins > 0 && mins <= 120) {
                                this.plugin.settings.pomodoroWorkMinutes = mins;
                                await this.plugin.saveSettings();
                                if (timer.mode === 'idle') {
                                    timer.timeRemaining = mins * 60;
                                    timer.totalTime = mins * 60;
                                    this.render();
                                }
                                this.persistTimersToStorage();
                            }
                        }
                    ).open();
                });
        });

        menu.addSeparator();

        menu.addItem((item) => {
            item.setTitle('Break Duration').setDisabled(true);
        });

        const breakOptions = [5, 10, 15];
        breakOptions.forEach((mins) => {
            menu.addItem((item) => {
                const current = this.plugin.settings.pomodoroBreakMinutes;
                item.setTitle(`  ${mins} min${current === mins ? ' ✓' : ''}`)
                    .onClick(async () => {
                        this.plugin.settings.pomodoroBreakMinutes = mins;
                        await this.plugin.saveSettings();
                        this.persistTimersToStorage();
                    });
            });
        });

        menu.addItem((item) => {
            const current = this.plugin.settings.pomodoroBreakMinutes;
            const isCustom = !breakOptions.includes(current);
            item.setTitle(`  Custom...${isCustom ? ` (${current}min) ✓` : ''}`)
                .onClick(() => {
                    new InputModal(
                        this.app,
                        'Break Duration',
                        'Minutes (1-60)',
                        current.toString(),
                        async (value) => {
                            const mins = parseInt(value);
                            if (!isNaN(mins) && mins > 0 && mins <= 60) {
                                this.plugin.settings.pomodoroBreakMinutes = mins;
                                await this.plugin.saveSettings();
                                this.persistTimersToStorage();
                            }
                        }
                    ).open();
                });
        });

        menu.addSeparator();

        // Auto Repeat toggle
        menu.addItem((item) => {
            item.setTitle(`Auto Repeat${timer.autoRepeat ? ' ✓' : ''}`)
                .onClick(() => {
                    timer.autoRepeat = !timer.autoRepeat;
                    this.persistTimersToStorage();
                });
        });

        menu.showAtMouseEvent(e);
    }

    destroy(): void {
        for (const [taskId] of this.timers) {
            this.stopTimer(taskId);
        }
        this.timers.clear();
        if (this.container) {
            this.container.remove();
            this.container = null;
        }
    }
}
