/**
 * Timer Instance Type Definition
 *
 * Shared types for timer instances used by TimerWidget / TimerRecorder / TimerProgressUI.
 */

export type TimerPhase = 'idle' | 'work' | 'break' | 'prepare';

export interface TimerBase {
    id: string;
    taskId: string;
    taskName: string;
    taskOriginalText: string;
    taskFile: string;
    timerTargetId?: string;
    autoGeneratedTargetId?: boolean;

    startTimeMs: number;
    pausedElapsedTime: number;

    phase: TimerPhase;
    isRunning: boolean;
    isExpanded: boolean;
    intervalId: number | null;

    customLabel: string;
    recordMode: 'child' | 'self';
    parserId: string;
}

export interface PomodoroTimer extends TimerBase {
    timerType: 'pomodoro';
    timeRemaining: number;
    totalTime: number;
    autoRepeat: boolean;
}

export interface CountupTimer extends TimerBase {
    timerType: 'countup';
    elapsedTime: number;
}

export interface CountdownTimer extends TimerBase {
    timerType: 'countdown';
    timeRemaining: number;
    totalTime: number;
    elapsedTime: number;
}

export interface IntervalSegment {
    label: string;
    durationSeconds: number;
    type: 'work' | 'break' | 'prepare';
}

export interface IntervalGroup {
    segments: IntervalSegment[];
    repeatCount: number;
}

export interface IntervalTimer extends TimerBase {
    timerType: 'interval';
    groups: IntervalGroup[];
    currentGroupIndex: number;
    currentSegmentIndex: number;
    currentRepeatIndex: number;
    segmentTimeRemaining: number;
    totalElapsedTime: number;
    totalDuration: number;
}

export interface IdleTimer extends TimerBase {
    timerType: 'idle';
    elapsedTime: number;
}

export type TimerInstance = PomodoroTimer | CountupTimer | CountdownTimer | IntervalTimer | IdleTimer;
export type TimerType = TimerInstance['timerType'];

export interface TimerStartConfig {
    taskId: string;
    taskName: string;
    taskOriginalText?: string;
    taskFile?: string;
    recordMode?: 'child' | 'self';
    parserId?: string;
    timerTargetId?: string;
    timerType: TimerType;
    autoStart?: boolean;
    countdownSeconds?: number;
    intervalGroups?: IntervalGroup[];
}

export function getTimerElapsedSeconds(timer: TimerInstance): number {
    switch (timer.timerType) {
        case 'countup':
        case 'countdown':
        case 'idle':
            return timer.elapsedTime;
        case 'interval':
            return timer.totalElapsedTime;
        case 'pomodoro':
            return Math.max(0, timer.totalTime - timer.timeRemaining);
        default:
            return 0;
    }
}

